// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AuthConfigAzureadInitParameters struct {

	// Access mode for auth. required, restricted, unrestricted are supported. Default unrestricted (string)
	AccessMode *string `json:"accessMode,omitempty" tf:"access_mode,omitempty"`

	// Allowed principal ids for auth. Required if access_mode is required or restricted. Ex: azuread_user://<USER_ID>  azuread_group://<GROUP_ID> (list)
	AllowedPrincipalIds []*string `json:"allowedPrincipalIds,omitempty" tf:"allowed_principal_ids,omitempty"`

	// Annotations of the resource (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// AzureAD auth application ID (string)
	ApplicationIDSecretRef v1.SecretKeySelector `json:"applicationIdSecretRef" tf:"-"`

	// AzureAD auth application secret (string)
	ApplicationSecretSecretRef v1.SecretKeySelector `json:"applicationSecretSecretRef" tf:"-"`

	// AzureAD auth endpoint (string)
	AuthEndpoint *string `json:"authEndpoint,omitempty" tf:"auth_endpoint,omitempty"`

	// Enable auth config provider. Default true (bool)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// AzureAD endpoint. Default https://login.microsoftonline.com/ (string)
	Endpoint *string `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// AzureAD graph endpoint (string)
	GraphEndpoint *string `json:"graphEndpoint,omitempty" tf:"graph_endpoint,omitempty"`

	GroupMembershipFilter *string `json:"groupMembershipFilter,omitempty" tf:"group_membership_filter,omitempty"`

	// Labels of the resource (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Rancher URL (string). "<rancher_url>/verify-auth-azure"
	RancherURL *string `json:"rancherUrl,omitempty" tf:"rancher_url,omitempty"`

	// AzureAD tenant ID (string)
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// AzureAD token endpoint (string)
	TokenEndpoint *string `json:"tokenEndpoint,omitempty" tf:"token_endpoint,omitempty"`
}

type AuthConfigAzureadObservation struct {

	// Access mode for auth. required, restricted, unrestricted are supported. Default unrestricted (string)
	AccessMode *string `json:"accessMode,omitempty" tf:"access_mode,omitempty"`

	// Allowed principal ids for auth. Required if access_mode is required or restricted. Ex: azuread_user://<USER_ID>  azuread_group://<GROUP_ID> (list)
	AllowedPrincipalIds []*string `json:"allowedPrincipalIds,omitempty" tf:"allowed_principal_ids,omitempty"`

	// Annotations of the resource (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// AzureAD auth endpoint (string)
	AuthEndpoint *string `json:"authEndpoint,omitempty" tf:"auth_endpoint,omitempty"`

	// Enable auth config provider. Default true (bool)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// AzureAD endpoint. Default https://login.microsoftonline.com/ (string)
	Endpoint *string `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// AzureAD graph endpoint (string)
	GraphEndpoint *string `json:"graphEndpoint,omitempty" tf:"graph_endpoint,omitempty"`

	GroupMembershipFilter *string `json:"groupMembershipFilter,omitempty" tf:"group_membership_filter,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels of the resource (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Computed) The name of the resource (string)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Rancher URL (string). "<rancher_url>/verify-auth-azure"
	RancherURL *string `json:"rancherUrl,omitempty" tf:"rancher_url,omitempty"`

	// AzureAD tenant ID (string)
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// AzureAD token endpoint (string)
	TokenEndpoint *string `json:"tokenEndpoint,omitempty" tf:"token_endpoint,omitempty"`

	// (Computed) The type of the resource (string)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type AuthConfigAzureadParameters struct {

	// Access mode for auth. required, restricted, unrestricted are supported. Default unrestricted (string)
	// +kubebuilder:validation:Optional
	AccessMode *string `json:"accessMode,omitempty" tf:"access_mode,omitempty"`

	// Allowed principal ids for auth. Required if access_mode is required or restricted. Ex: azuread_user://<USER_ID>  azuread_group://<GROUP_ID> (list)
	// +kubebuilder:validation:Optional
	AllowedPrincipalIds []*string `json:"allowedPrincipalIds,omitempty" tf:"allowed_principal_ids,omitempty"`

	// Annotations of the resource (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// AzureAD auth application ID (string)
	// +kubebuilder:validation:Optional
	ApplicationIDSecretRef v1.SecretKeySelector `json:"applicationIdSecretRef" tf:"-"`

	// AzureAD auth application secret (string)
	// +kubebuilder:validation:Optional
	ApplicationSecretSecretRef v1.SecretKeySelector `json:"applicationSecretSecretRef" tf:"-"`

	// AzureAD auth endpoint (string)
	// +kubebuilder:validation:Optional
	AuthEndpoint *string `json:"authEndpoint,omitempty" tf:"auth_endpoint,omitempty"`

	// Enable auth config provider. Default true (bool)
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// AzureAD endpoint. Default https://login.microsoftonline.com/ (string)
	// +kubebuilder:validation:Optional
	Endpoint *string `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// AzureAD graph endpoint (string)
	// +kubebuilder:validation:Optional
	GraphEndpoint *string `json:"graphEndpoint,omitempty" tf:"graph_endpoint,omitempty"`

	// +kubebuilder:validation:Optional
	GroupMembershipFilter *string `json:"groupMembershipFilter,omitempty" tf:"group_membership_filter,omitempty"`

	// Labels of the resource (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Rancher URL (string). "<rancher_url>/verify-auth-azure"
	// +kubebuilder:validation:Optional
	RancherURL *string `json:"rancherUrl,omitempty" tf:"rancher_url,omitempty"`

	// AzureAD tenant ID (string)
	// +kubebuilder:validation:Optional
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// AzureAD token endpoint (string)
	// +kubebuilder:validation:Optional
	TokenEndpoint *string `json:"tokenEndpoint,omitempty" tf:"token_endpoint,omitempty"`
}

// AuthConfigAzureadSpec defines the desired state of AuthConfigAzuread
type AuthConfigAzureadSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AuthConfigAzureadParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AuthConfigAzureadInitParameters `json:"initProvider,omitempty"`
}

// AuthConfigAzureadStatus defines the observed state of AuthConfigAzuread.
type AuthConfigAzureadStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AuthConfigAzureadObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AuthConfigAzuread is the Schema for the AuthConfigAzureads API. Provides a Rancher v2 Auth Config AzureAD resource. This can be used to configure and enable Auth Config AzureAD for Rancher v2 RKE clusters and retrieve their information.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rancher2}
type AuthConfigAzuread struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.applicationIdSecretRef)",message="spec.forProvider.applicationIdSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.applicationSecretSecretRef)",message="spec.forProvider.applicationSecretSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.authEndpoint) || (has(self.initProvider) && has(self.initProvider.authEndpoint))",message="spec.forProvider.authEndpoint is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.graphEndpoint) || (has(self.initProvider) && has(self.initProvider.graphEndpoint))",message="spec.forProvider.graphEndpoint is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.rancherUrl) || (has(self.initProvider) && has(self.initProvider.rancherUrl))",message="spec.forProvider.rancherUrl is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.tenantId) || (has(self.initProvider) && has(self.initProvider.tenantId))",message="spec.forProvider.tenantId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.tokenEndpoint) || (has(self.initProvider) && has(self.initProvider.tokenEndpoint))",message="spec.forProvider.tokenEndpoint is a required parameter"
	Spec   AuthConfigAzureadSpec   `json:"spec"`
	Status AuthConfigAzureadStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AuthConfigAzureadList contains a list of AuthConfigAzureads
type AuthConfigAzureadList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AuthConfigAzuread `json:"items"`
}

// Repository type metadata.
var (
	AuthConfigAzuread_Kind             = "AuthConfigAzuread"
	AuthConfigAzuread_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AuthConfigAzuread_Kind}.String()
	AuthConfigAzuread_KindAPIVersion   = AuthConfigAzuread_Kind + "." + CRDGroupVersion.String()
	AuthConfigAzuread_GroupVersionKind = CRDGroupVersion.WithKind(AuthConfigAzuread_Kind)
)

func init() {
	SchemeBuilder.Register(&AuthConfigAzuread{}, &AuthConfigAzureadList{})
}
