// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AuthConfigKeycloakInitParameters struct {

	// Access mode for auth. required, restricted, unrestricted are supported. Default unrestricted (string)
	AccessMode *string `json:"accessMode,omitempty" tf:"access_mode,omitempty"`

	// Allowed principal ids for auth. Required if access_mode is required or restricted. Ex: keycloak_user://<USER_ID>  keycloak_group://<GROUP_ID> (list)
	AllowedPrincipalIds []*string `json:"allowedPrincipalIds,omitempty" tf:"allowed_principal_ids,omitempty"`

	// Annotations of the resource (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// KeyCloak display name field (string)
	DisplayNameField *string `json:"displayNameField,omitempty" tf:"display_name_field,omitempty"`

	// Enable auth config provider. Default true (bool)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// KeyCloak Client ID field (string)
	EntityID *string `json:"entityId,omitempty" tf:"entity_id,omitempty"`

	// KeyCloak group field (string)
	GroupsField *string `json:"groupsField,omitempty" tf:"groups_field,omitempty"`

	// KeyCloak IDP metadata content (string)
	IdpMetadataContentSecretRef v1.SecretKeySelector `json:"idpMetadataContentSecretRef" tf:"-"`

	// Labels of the resource (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Rancher URL. URL scheme needs to be specified, https://<RANCHER_API_HOST> (string)
	RancherAPIHost *string `json:"rancherApiHost,omitempty" tf:"rancher_api_host,omitempty"`

	// KeyCloak SP cert (string)
	SpCertSecretRef v1.SecretKeySelector `json:"spCertSecretRef" tf:"-"`

	// KeyCloak SP key (string)
	SpKeySecretRef v1.SecretKeySelector `json:"spKeySecretRef" tf:"-"`

	// KeyCloak UID field (string)
	UIDField *string `json:"uidField,omitempty" tf:"uid_field,omitempty"`

	// KeyCloak user name field (string)
	UserNameField *string `json:"userNameField,omitempty" tf:"user_name_field,omitempty"`
}

type AuthConfigKeycloakObservation struct {

	// Access mode for auth. required, restricted, unrestricted are supported. Default unrestricted (string)
	AccessMode *string `json:"accessMode,omitempty" tf:"access_mode,omitempty"`

	// Allowed principal ids for auth. Required if access_mode is required or restricted. Ex: keycloak_user://<USER_ID>  keycloak_group://<GROUP_ID> (list)
	AllowedPrincipalIds []*string `json:"allowedPrincipalIds,omitempty" tf:"allowed_principal_ids,omitempty"`

	// Annotations of the resource (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// KeyCloak display name field (string)
	DisplayNameField *string `json:"displayNameField,omitempty" tf:"display_name_field,omitempty"`

	// Enable auth config provider. Default true (bool)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// KeyCloak Client ID field (string)
	EntityID *string `json:"entityId,omitempty" tf:"entity_id,omitempty"`

	// KeyCloak group field (string)
	GroupsField *string `json:"groupsField,omitempty" tf:"groups_field,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels of the resource (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Computed) The name of the resource (string)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Rancher URL. URL scheme needs to be specified, https://<RANCHER_API_HOST> (string)
	RancherAPIHost *string `json:"rancherApiHost,omitempty" tf:"rancher_api_host,omitempty"`

	// (Computed) The type of the resource (string)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// KeyCloak UID field (string)
	UIDField *string `json:"uidField,omitempty" tf:"uid_field,omitempty"`

	// KeyCloak user name field (string)
	UserNameField *string `json:"userNameField,omitempty" tf:"user_name_field,omitempty"`
}

type AuthConfigKeycloakParameters struct {

	// Access mode for auth. required, restricted, unrestricted are supported. Default unrestricted (string)
	// +kubebuilder:validation:Optional
	AccessMode *string `json:"accessMode,omitempty" tf:"access_mode,omitempty"`

	// Allowed principal ids for auth. Required if access_mode is required or restricted. Ex: keycloak_user://<USER_ID>  keycloak_group://<GROUP_ID> (list)
	// +kubebuilder:validation:Optional
	AllowedPrincipalIds []*string `json:"allowedPrincipalIds,omitempty" tf:"allowed_principal_ids,omitempty"`

	// Annotations of the resource (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// KeyCloak display name field (string)
	// +kubebuilder:validation:Optional
	DisplayNameField *string `json:"displayNameField,omitempty" tf:"display_name_field,omitempty"`

	// Enable auth config provider. Default true (bool)
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// KeyCloak Client ID field (string)
	// +kubebuilder:validation:Optional
	EntityID *string `json:"entityId,omitempty" tf:"entity_id,omitempty"`

	// KeyCloak group field (string)
	// +kubebuilder:validation:Optional
	GroupsField *string `json:"groupsField,omitempty" tf:"groups_field,omitempty"`

	// KeyCloak IDP metadata content (string)
	// +kubebuilder:validation:Optional
	IdpMetadataContentSecretRef v1.SecretKeySelector `json:"idpMetadataContentSecretRef" tf:"-"`

	// Labels of the resource (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Rancher URL. URL scheme needs to be specified, https://<RANCHER_API_HOST> (string)
	// +kubebuilder:validation:Optional
	RancherAPIHost *string `json:"rancherApiHost,omitempty" tf:"rancher_api_host,omitempty"`

	// KeyCloak SP cert (string)
	// +kubebuilder:validation:Optional
	SpCertSecretRef v1.SecretKeySelector `json:"spCertSecretRef" tf:"-"`

	// KeyCloak SP key (string)
	// +kubebuilder:validation:Optional
	SpKeySecretRef v1.SecretKeySelector `json:"spKeySecretRef" tf:"-"`

	// KeyCloak UID field (string)
	// +kubebuilder:validation:Optional
	UIDField *string `json:"uidField,omitempty" tf:"uid_field,omitempty"`

	// KeyCloak user name field (string)
	// +kubebuilder:validation:Optional
	UserNameField *string `json:"userNameField,omitempty" tf:"user_name_field,omitempty"`
}

// AuthConfigKeycloakSpec defines the desired state of AuthConfigKeycloak
type AuthConfigKeycloakSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AuthConfigKeycloakParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AuthConfigKeycloakInitParameters `json:"initProvider,omitempty"`
}

// AuthConfigKeycloakStatus defines the observed state of AuthConfigKeycloak.
type AuthConfigKeycloakStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AuthConfigKeycloakObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AuthConfigKeycloak is the Schema for the AuthConfigKeycloaks API. Provides a Rancher v2 Auth Config KeyCloak resource. This can be used to configure and enable Auth Config KeyCloak for Rancher v2 RKE clusters and retrieve their information.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rancher2}
type AuthConfigKeycloak struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayNameField) || (has(self.initProvider) && has(self.initProvider.displayNameField))",message="spec.forProvider.displayNameField is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.groupsField) || (has(self.initProvider) && has(self.initProvider.groupsField))",message="spec.forProvider.groupsField is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.idpMetadataContentSecretRef)",message="spec.forProvider.idpMetadataContentSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.rancherApiHost) || (has(self.initProvider) && has(self.initProvider.rancherApiHost))",message="spec.forProvider.rancherApiHost is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.spCertSecretRef)",message="spec.forProvider.spCertSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.spKeySecretRef)",message="spec.forProvider.spKeySecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.uidField) || (has(self.initProvider) && has(self.initProvider.uidField))",message="spec.forProvider.uidField is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.userNameField) || (has(self.initProvider) && has(self.initProvider.userNameField))",message="spec.forProvider.userNameField is a required parameter"
	Spec   AuthConfigKeycloakSpec   `json:"spec"`
	Status AuthConfigKeycloakStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AuthConfigKeycloakList contains a list of AuthConfigKeycloaks
type AuthConfigKeycloakList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AuthConfigKeycloak `json:"items"`
}

// Repository type metadata.
var (
	AuthConfigKeycloak_Kind             = "AuthConfigKeycloak"
	AuthConfigKeycloak_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AuthConfigKeycloak_Kind}.String()
	AuthConfigKeycloak_KindAPIVersion   = AuthConfigKeycloak_Kind + "." + CRDGroupVersion.String()
	AuthConfigKeycloak_GroupVersionKind = CRDGroupVersion.WithKind(AuthConfigKeycloak_Kind)
)

func init() {
	SchemeBuilder.Register(&AuthConfigKeycloak{}, &AuthConfigKeycloakList{})
}
