// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AuthConfigActivedirectoryInitParameters struct {

	// Access mode for auth. required, restricted, unrestricted are supported. Default unrestricted (string)
	AccessMode *string `json:"accessMode,omitempty" tf:"access_mode,omitempty"`

	// Allowed principal ids for auth. Required if access_mode is required or restricted. Ex: activedirectory_user://<DN>  activedirectory_group://<DN>. The local admin (local://<admin id>) and the test_username must be added too. (list)
	AllowedPrincipalIds []*string `json:"allowedPrincipalIds,omitempty" tf:"allowed_principal_ids,omitempty"`

	// Annotations of the resource (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// CA certificate for TLS if selfsigned (string)
	CertificateSecretRef *v1.SecretKeySelector `json:"certificateSecretRef,omitempty" tf:"-"`

	// ActiveDirectory connection timeout. Default 5000 (int)
	ConnectionTimeout *float64 `json:"connectionTimeout,omitempty" tf:"connection_timeout,omitempty"`

	// ActiveDirectory defult login domain (string)
	DefaultLoginDomain *string `json:"defaultLoginDomain,omitempty" tf:"default_login_domain,omitempty"`

	// Enable auth config provider. Default true (bool)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Group DN attribute. Default distinguishedName (string)
	GroupDnAttribute *string `json:"groupDnAttribute,omitempty" tf:"group_dn_attribute,omitempty"`

	// Group member mapping attribute. Default member (string)
	GroupMemberMappingAttribute *string `json:"groupMemberMappingAttribute,omitempty" tf:"group_member_mapping_attribute,omitempty"`

	// Group member user attribute. Default distinguishedName (string)
	GroupMemberUserAttribute *string `json:"groupMemberUserAttribute,omitempty" tf:"group_member_user_attribute,omitempty"`

	// Group name attribute. Default name (string)
	GroupNameAttribute *string `json:"groupNameAttribute,omitempty" tf:"group_name_attribute,omitempty"`

	// Group object class. Default group (string)
	GroupObjectClass *string `json:"groupObjectClass,omitempty" tf:"group_object_class,omitempty"`

	// Group search attribute. Default sAMAccountName (string)
	GroupSearchAttribute *string `json:"groupSearchAttribute,omitempty" tf:"group_search_attribute,omitempty"`

	// Group search base (string)
	GroupSearchBase *string `json:"groupSearchBase,omitempty" tf:"group_search_base,omitempty"`

	// Group search filter (string)
	GroupSearchFilter *string `json:"groupSearchFilter,omitempty" tf:"group_search_filter,omitempty"`

	// Labels of the resource (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Nested group membership enable. Default false (bool)
	NestedGroupMembershipEnabled *bool `json:"nestedGroupMembershipEnabled,omitempty" tf:"nested_group_membership_enabled,omitempty"`

	// ActiveDirectory port. Default 389 (int)
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// ActiveDirectory servers list (list)
	Servers []*string `json:"servers,omitempty" tf:"servers,omitempty"`

	// Service account password for access ActiveDirectory service (string)
	ServiceAccountPasswordSecretRef v1.SecretKeySelector `json:"serviceAccountPasswordSecretRef" tf:"-"`

	// Service account DN for access ActiveDirectory service (string)
	ServiceAccountUsernameSecretRef v1.SecretKeySelector `json:"serviceAccountUsernameSecretRef" tf:"-"`

	// Enable start TLS connection (bool)
	StartTLS *bool `json:"startTls,omitempty" tf:"start_tls,omitempty"`

	// Enable TLS connection (bool)
	TLS *bool `json:"tls,omitempty" tf:"tls,omitempty"`

	// Password for test access to ActiveDirectory service (string)
	TestPasswordSecretRef v1.SecretKeySelector `json:"testPasswordSecretRef" tf:"-"`

	// Username for test access to ActiveDirectory service (string)
	TestUsername *string `json:"testUsername,omitempty" tf:"test_username,omitempty"`

	// User disabled bit mask. Default 2 (int)
	UserDisabledBitMask *float64 `json:"userDisabledBitMask,omitempty" tf:"user_disabled_bit_mask,omitempty"`

	// User enable attribute (string)
	UserEnabledAttribute *string `json:"userEnabledAttribute,omitempty" tf:"user_enabled_attribute,omitempty"`

	// User login attribute. Default sAMAccountName (string)
	UserLoginAttribute *string `json:"userLoginAttribute,omitempty" tf:"user_login_attribute,omitempty"`

	// User name attribute. Default name (string)
	UserNameAttribute *string `json:"userNameAttribute,omitempty" tf:"user_name_attribute,omitempty"`

	// User object class. Default person (string)
	UserObjectClass *string `json:"userObjectClass,omitempty" tf:"user_object_class,omitempty"`

	// User search attribute. Default sAMAccountName|sn|givenName (string)
	UserSearchAttribute *string `json:"userSearchAttribute,omitempty" tf:"user_search_attribute,omitempty"`

	// User search base DN (string)
	UserSearchBase *string `json:"userSearchBase,omitempty" tf:"user_search_base,omitempty"`

	// User search filter (string)
	UserSearchFilter *string `json:"userSearchFilter,omitempty" tf:"user_search_filter,omitempty"`
}

type AuthConfigActivedirectoryObservation struct {

	// Access mode for auth. required, restricted, unrestricted are supported. Default unrestricted (string)
	AccessMode *string `json:"accessMode,omitempty" tf:"access_mode,omitempty"`

	// Allowed principal ids for auth. Required if access_mode is required or restricted. Ex: activedirectory_user://<DN>  activedirectory_group://<DN>. The local admin (local://<admin id>) and the test_username must be added too. (list)
	AllowedPrincipalIds []*string `json:"allowedPrincipalIds,omitempty" tf:"allowed_principal_ids,omitempty"`

	// Annotations of the resource (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// ActiveDirectory connection timeout. Default 5000 (int)
	ConnectionTimeout *float64 `json:"connectionTimeout,omitempty" tf:"connection_timeout,omitempty"`

	// ActiveDirectory defult login domain (string)
	DefaultLoginDomain *string `json:"defaultLoginDomain,omitempty" tf:"default_login_domain,omitempty"`

	// Enable auth config provider. Default true (bool)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Group DN attribute. Default distinguishedName (string)
	GroupDnAttribute *string `json:"groupDnAttribute,omitempty" tf:"group_dn_attribute,omitempty"`

	// Group member mapping attribute. Default member (string)
	GroupMemberMappingAttribute *string `json:"groupMemberMappingAttribute,omitempty" tf:"group_member_mapping_attribute,omitempty"`

	// Group member user attribute. Default distinguishedName (string)
	GroupMemberUserAttribute *string `json:"groupMemberUserAttribute,omitempty" tf:"group_member_user_attribute,omitempty"`

	// Group name attribute. Default name (string)
	GroupNameAttribute *string `json:"groupNameAttribute,omitempty" tf:"group_name_attribute,omitempty"`

	// Group object class. Default group (string)
	GroupObjectClass *string `json:"groupObjectClass,omitempty" tf:"group_object_class,omitempty"`

	// Group search attribute. Default sAMAccountName (string)
	GroupSearchAttribute *string `json:"groupSearchAttribute,omitempty" tf:"group_search_attribute,omitempty"`

	// Group search base (string)
	GroupSearchBase *string `json:"groupSearchBase,omitempty" tf:"group_search_base,omitempty"`

	// Group search filter (string)
	GroupSearchFilter *string `json:"groupSearchFilter,omitempty" tf:"group_search_filter,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels of the resource (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Computed) The name of the resource (string)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Nested group membership enable. Default false (bool)
	NestedGroupMembershipEnabled *bool `json:"nestedGroupMembershipEnabled,omitempty" tf:"nested_group_membership_enabled,omitempty"`

	// ActiveDirectory port. Default 389 (int)
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// ActiveDirectory servers list (list)
	Servers []*string `json:"servers,omitempty" tf:"servers,omitempty"`

	// Enable start TLS connection (bool)
	StartTLS *bool `json:"startTls,omitempty" tf:"start_tls,omitempty"`

	// Enable TLS connection (bool)
	TLS *bool `json:"tls,omitempty" tf:"tls,omitempty"`

	// Username for test access to ActiveDirectory service (string)
	TestUsername *string `json:"testUsername,omitempty" tf:"test_username,omitempty"`

	// (Computed) The type of the resource (string)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// User disabled bit mask. Default 2 (int)
	UserDisabledBitMask *float64 `json:"userDisabledBitMask,omitempty" tf:"user_disabled_bit_mask,omitempty"`

	// User enable attribute (string)
	UserEnabledAttribute *string `json:"userEnabledAttribute,omitempty" tf:"user_enabled_attribute,omitempty"`

	// User login attribute. Default sAMAccountName (string)
	UserLoginAttribute *string `json:"userLoginAttribute,omitempty" tf:"user_login_attribute,omitempty"`

	// User name attribute. Default name (string)
	UserNameAttribute *string `json:"userNameAttribute,omitempty" tf:"user_name_attribute,omitempty"`

	// User object class. Default person (string)
	UserObjectClass *string `json:"userObjectClass,omitempty" tf:"user_object_class,omitempty"`

	// User search attribute. Default sAMAccountName|sn|givenName (string)
	UserSearchAttribute *string `json:"userSearchAttribute,omitempty" tf:"user_search_attribute,omitempty"`

	// User search base DN (string)
	UserSearchBase *string `json:"userSearchBase,omitempty" tf:"user_search_base,omitempty"`

	// User search filter (string)
	UserSearchFilter *string `json:"userSearchFilter,omitempty" tf:"user_search_filter,omitempty"`
}

type AuthConfigActivedirectoryParameters struct {

	// Access mode for auth. required, restricted, unrestricted are supported. Default unrestricted (string)
	// +kubebuilder:validation:Optional
	AccessMode *string `json:"accessMode,omitempty" tf:"access_mode,omitempty"`

	// Allowed principal ids for auth. Required if access_mode is required or restricted. Ex: activedirectory_user://<DN>  activedirectory_group://<DN>. The local admin (local://<admin id>) and the test_username must be added too. (list)
	// +kubebuilder:validation:Optional
	AllowedPrincipalIds []*string `json:"allowedPrincipalIds,omitempty" tf:"allowed_principal_ids,omitempty"`

	// Annotations of the resource (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// CA certificate for TLS if selfsigned (string)
	// +kubebuilder:validation:Optional
	CertificateSecretRef *v1.SecretKeySelector `json:"certificateSecretRef,omitempty" tf:"-"`

	// ActiveDirectory connection timeout. Default 5000 (int)
	// +kubebuilder:validation:Optional
	ConnectionTimeout *float64 `json:"connectionTimeout,omitempty" tf:"connection_timeout,omitempty"`

	// ActiveDirectory defult login domain (string)
	// +kubebuilder:validation:Optional
	DefaultLoginDomain *string `json:"defaultLoginDomain,omitempty" tf:"default_login_domain,omitempty"`

	// Enable auth config provider. Default true (bool)
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Group DN attribute. Default distinguishedName (string)
	// +kubebuilder:validation:Optional
	GroupDnAttribute *string `json:"groupDnAttribute,omitempty" tf:"group_dn_attribute,omitempty"`

	// Group member mapping attribute. Default member (string)
	// +kubebuilder:validation:Optional
	GroupMemberMappingAttribute *string `json:"groupMemberMappingAttribute,omitempty" tf:"group_member_mapping_attribute,omitempty"`

	// Group member user attribute. Default distinguishedName (string)
	// +kubebuilder:validation:Optional
	GroupMemberUserAttribute *string `json:"groupMemberUserAttribute,omitempty" tf:"group_member_user_attribute,omitempty"`

	// Group name attribute. Default name (string)
	// +kubebuilder:validation:Optional
	GroupNameAttribute *string `json:"groupNameAttribute,omitempty" tf:"group_name_attribute,omitempty"`

	// Group object class. Default group (string)
	// +kubebuilder:validation:Optional
	GroupObjectClass *string `json:"groupObjectClass,omitempty" tf:"group_object_class,omitempty"`

	// Group search attribute. Default sAMAccountName (string)
	// +kubebuilder:validation:Optional
	GroupSearchAttribute *string `json:"groupSearchAttribute,omitempty" tf:"group_search_attribute,omitempty"`

	// Group search base (string)
	// +kubebuilder:validation:Optional
	GroupSearchBase *string `json:"groupSearchBase,omitempty" tf:"group_search_base,omitempty"`

	// Group search filter (string)
	// +kubebuilder:validation:Optional
	GroupSearchFilter *string `json:"groupSearchFilter,omitempty" tf:"group_search_filter,omitempty"`

	// Labels of the resource (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Nested group membership enable. Default false (bool)
	// +kubebuilder:validation:Optional
	NestedGroupMembershipEnabled *bool `json:"nestedGroupMembershipEnabled,omitempty" tf:"nested_group_membership_enabled,omitempty"`

	// ActiveDirectory port. Default 389 (int)
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// ActiveDirectory servers list (list)
	// +kubebuilder:validation:Optional
	Servers []*string `json:"servers,omitempty" tf:"servers,omitempty"`

	// Service account password for access ActiveDirectory service (string)
	// +kubebuilder:validation:Optional
	ServiceAccountPasswordSecretRef v1.SecretKeySelector `json:"serviceAccountPasswordSecretRef" tf:"-"`

	// Service account DN for access ActiveDirectory service (string)
	// +kubebuilder:validation:Optional
	ServiceAccountUsernameSecretRef v1.SecretKeySelector `json:"serviceAccountUsernameSecretRef" tf:"-"`

	// Enable start TLS connection (bool)
	// +kubebuilder:validation:Optional
	StartTLS *bool `json:"startTls,omitempty" tf:"start_tls,omitempty"`

	// Enable TLS connection (bool)
	// +kubebuilder:validation:Optional
	TLS *bool `json:"tls,omitempty" tf:"tls,omitempty"`

	// Password for test access to ActiveDirectory service (string)
	// +kubebuilder:validation:Optional
	TestPasswordSecretRef v1.SecretKeySelector `json:"testPasswordSecretRef" tf:"-"`

	// Username for test access to ActiveDirectory service (string)
	// +kubebuilder:validation:Optional
	TestUsername *string `json:"testUsername,omitempty" tf:"test_username,omitempty"`

	// User disabled bit mask. Default 2 (int)
	// +kubebuilder:validation:Optional
	UserDisabledBitMask *float64 `json:"userDisabledBitMask,omitempty" tf:"user_disabled_bit_mask,omitempty"`

	// User enable attribute (string)
	// +kubebuilder:validation:Optional
	UserEnabledAttribute *string `json:"userEnabledAttribute,omitempty" tf:"user_enabled_attribute,omitempty"`

	// User login attribute. Default sAMAccountName (string)
	// +kubebuilder:validation:Optional
	UserLoginAttribute *string `json:"userLoginAttribute,omitempty" tf:"user_login_attribute,omitempty"`

	// User name attribute. Default name (string)
	// +kubebuilder:validation:Optional
	UserNameAttribute *string `json:"userNameAttribute,omitempty" tf:"user_name_attribute,omitempty"`

	// User object class. Default person (string)
	// +kubebuilder:validation:Optional
	UserObjectClass *string `json:"userObjectClass,omitempty" tf:"user_object_class,omitempty"`

	// User search attribute. Default sAMAccountName|sn|givenName (string)
	// +kubebuilder:validation:Optional
	UserSearchAttribute *string `json:"userSearchAttribute,omitempty" tf:"user_search_attribute,omitempty"`

	// User search base DN (string)
	// +kubebuilder:validation:Optional
	UserSearchBase *string `json:"userSearchBase,omitempty" tf:"user_search_base,omitempty"`

	// User search filter (string)
	// +kubebuilder:validation:Optional
	UserSearchFilter *string `json:"userSearchFilter,omitempty" tf:"user_search_filter,omitempty"`
}

// AuthConfigActivedirectorySpec defines the desired state of AuthConfigActivedirectory
type AuthConfigActivedirectorySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AuthConfigActivedirectoryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AuthConfigActivedirectoryInitParameters `json:"initProvider,omitempty"`
}

// AuthConfigActivedirectoryStatus defines the observed state of AuthConfigActivedirectory.
type AuthConfigActivedirectoryStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AuthConfigActivedirectoryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AuthConfigActivedirectory is the Schema for the AuthConfigActivedirectorys API. Provides a Rancher v2 Auth Config ActiveDirectory resource. This can be used to configure and enable Auth Config ActiveDirectory for Rancher v2 RKE clusters and retrieve their information.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rancher2}
type AuthConfigActivedirectory struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.servers) || (has(self.initProvider) && has(self.initProvider.servers))",message="spec.forProvider.servers is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceAccountPasswordSecretRef)",message="spec.forProvider.serviceAccountPasswordSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceAccountUsernameSecretRef)",message="spec.forProvider.serviceAccountUsernameSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.testPasswordSecretRef)",message="spec.forProvider.testPasswordSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.testUsername) || (has(self.initProvider) && has(self.initProvider.testUsername))",message="spec.forProvider.testUsername is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.userSearchBase) || (has(self.initProvider) && has(self.initProvider.userSearchBase))",message="spec.forProvider.userSearchBase is a required parameter"
	Spec   AuthConfigActivedirectorySpec   `json:"spec"`
	Status AuthConfigActivedirectoryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AuthConfigActivedirectoryList contains a list of AuthConfigActivedirectorys
type AuthConfigActivedirectoryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AuthConfigActivedirectory `json:"items"`
}

// Repository type metadata.
var (
	AuthConfigActivedirectory_Kind             = "AuthConfigActivedirectory"
	AuthConfigActivedirectory_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AuthConfigActivedirectory_Kind}.String()
	AuthConfigActivedirectory_KindAPIVersion   = AuthConfigActivedirectory_Kind + "." + CRDGroupVersion.String()
	AuthConfigActivedirectory_GroupVersionKind = CRDGroupVersion.WithKind(AuthConfigActivedirectory_Kind)
)

func init() {
	SchemeBuilder.Register(&AuthConfigActivedirectory{}, &AuthConfigActivedirectoryList{})
}
