// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Certificate) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ConfigMapV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Namespace) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Project) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Registry) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Secret) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SecretV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *StorageClassV2) Hub() {}
