// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type StorageClassV2InitParameters struct {

	// Is the provisioner of the storageClass v2 allowing volume expansion? (bool)
	// StorageClass allow_volume_expansion
	AllowVolumeExpansion *bool `json:"allowVolumeExpansion,omitempty" tf:"allow_volume_expansion,omitempty"`

	// Annotations for the storageClass v2 (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The cluster id of the storageClass V2 (string)
	// K8s cluster ID
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/cluster/rancher/v1alpha1.ClusterV2
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// The provisioner of the storageClass v2 (string)
	// StorageClass provisioner
	K8SProvisioner *string `json:"k8sProvisioner,omitempty" tf:"k8s_provisioner,omitempty"`

	// Labels for the storageClass v2 (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The mount options for storageClass v2 (list)
	// StorageClass mount options
	MountOptions []*string `json:"mountOptions,omitempty" tf:"mount_options,omitempty"`

	// The name of the storageClass v2 (string)
	// StorageClass name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The parameters for storageClass v2 (string)
	// StorageClass provisioner paramaters
	// +mapType=granular
	Parameters map[string]*string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// The reclaim policy for storageClass v2. Delete, Recycle and Retain values are allowed. Default: Delete (string)
	// StorageClass provisioner reclaim policy
	ReclaimPolicy *string `json:"reclaimPolicy,omitempty" tf:"reclaim_policy,omitempty"`

	// The volume binding mode for storageClass v2. Immediate and WaitForFirstConsumer values are allowed. Default: Immediate (string)
	// StorageClass provisioner volume binding mode
	VolumeBindingMode *string `json:"volumeBindingMode,omitempty" tf:"volume_binding_mode,omitempty"`
}

type StorageClassV2Observation struct {

	// Is the provisioner of the storageClass v2 allowing volume expansion? (bool)
	// StorageClass allow_volume_expansion
	AllowVolumeExpansion *bool `json:"allowVolumeExpansion,omitempty" tf:"allow_volume_expansion,omitempty"`

	// Annotations for the storageClass v2 (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The cluster id of the storageClass V2 (string)
	// K8s cluster ID
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The provisioner of the storageClass v2 (string)
	// StorageClass provisioner
	K8SProvisioner *string `json:"k8sProvisioner,omitempty" tf:"k8s_provisioner,omitempty"`

	// Labels for the storageClass v2 (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The mount options for storageClass v2 (list)
	// StorageClass mount options
	MountOptions []*string `json:"mountOptions,omitempty" tf:"mount_options,omitempty"`

	// The name of the storageClass v2 (string)
	// StorageClass name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The parameters for storageClass v2 (string)
	// StorageClass provisioner paramaters
	// +mapType=granular
	Parameters map[string]*string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// The reclaim policy for storageClass v2. Delete, Recycle and Retain values are allowed. Default: Delete (string)
	// StorageClass provisioner reclaim policy
	ReclaimPolicy *string `json:"reclaimPolicy,omitempty" tf:"reclaim_policy,omitempty"`

	// (Computed) The k8s resource version (string)
	ResourceVersion *string `json:"resourceVersion,omitempty" tf:"resource_version,omitempty"`

	// The volume binding mode for storageClass v2. Immediate and WaitForFirstConsumer values are allowed. Default: Immediate (string)
	// StorageClass provisioner volume binding mode
	VolumeBindingMode *string `json:"volumeBindingMode,omitempty" tf:"volume_binding_mode,omitempty"`
}

type StorageClassV2Parameters struct {

	// Is the provisioner of the storageClass v2 allowing volume expansion? (bool)
	// StorageClass allow_volume_expansion
	// +kubebuilder:validation:Optional
	AllowVolumeExpansion *bool `json:"allowVolumeExpansion,omitempty" tf:"allow_volume_expansion,omitempty"`

	// Annotations for the storageClass v2 (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The cluster id of the storageClass V2 (string)
	// K8s cluster ID
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/cluster/rancher/v1alpha1.ClusterV2
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// The provisioner of the storageClass v2 (string)
	// StorageClass provisioner
	// +kubebuilder:validation:Optional
	K8SProvisioner *string `json:"k8sProvisioner,omitempty" tf:"k8s_provisioner,omitempty"`

	// Labels for the storageClass v2 (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The mount options for storageClass v2 (list)
	// StorageClass mount options
	// +kubebuilder:validation:Optional
	MountOptions []*string `json:"mountOptions,omitempty" tf:"mount_options,omitempty"`

	// The name of the storageClass v2 (string)
	// StorageClass name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The parameters for storageClass v2 (string)
	// StorageClass provisioner paramaters
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Parameters map[string]*string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// The reclaim policy for storageClass v2. Delete, Recycle and Retain values are allowed. Default: Delete (string)
	// StorageClass provisioner reclaim policy
	// +kubebuilder:validation:Optional
	ReclaimPolicy *string `json:"reclaimPolicy,omitempty" tf:"reclaim_policy,omitempty"`

	// The volume binding mode for storageClass v2. Immediate and WaitForFirstConsumer values are allowed. Default: Immediate (string)
	// StorageClass provisioner volume binding mode
	// +kubebuilder:validation:Optional
	VolumeBindingMode *string `json:"volumeBindingMode,omitempty" tf:"volume_binding_mode,omitempty"`
}

// StorageClassV2Spec defines the desired state of StorageClassV2
type StorageClassV2Spec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     StorageClassV2Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider StorageClassV2InitParameters `json:"initProvider,omitempty"`
}

// StorageClassV2Status defines the observed state of StorageClassV2.
type StorageClassV2Status struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        StorageClassV2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// StorageClassV2 is the Schema for the StorageClassV2s API. Provides a Rancher Storage Class v2 resource. This can be used to manage k8s storage classes for Rancher v2 clusters and retrieve their information. Storage Class v2 resource is available at Rancher v2.5.x and above.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rancher2}
type StorageClassV2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.k8sProvisioner) || (has(self.initProvider) && has(self.initProvider.k8sProvisioner))",message="spec.forProvider.k8sProvisioner is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   StorageClassV2Spec   `json:"spec"`
	Status StorageClassV2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// StorageClassV2List contains a list of StorageClassV2s
type StorageClassV2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []StorageClassV2 `json:"items"`
}

// Repository type metadata.
var (
	StorageClassV2_Kind             = "StorageClassV2"
	StorageClassV2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: StorageClassV2_Kind}.String()
	StorageClassV2_KindAPIVersion   = StorageClassV2_Kind + "." + CRDGroupVersion.String()
	StorageClassV2_GroupVersionKind = CRDGroupVersion.WithKind(StorageClassV2_Kind)
)

func init() {
	SchemeBuilder.Register(&StorageClassV2{}, &StorageClassV2List{})
}
