// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ClusterDriverInitParameters struct {

	// Specify the cluster driver state (bool)
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// Actual url of the cluster driver (string)
	ActualURL *string `json:"actualUrl,omitempty" tf:"actual_url,omitempty"`

	// Annotations of the resource (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Specify whether the cluster driver is an internal cluster driver or not (bool)
	Builtin *bool `json:"builtin,omitempty" tf:"builtin,omitempty"`

	// Verify that the downloaded driver matches the expected checksum (string)
	Checksum *string `json:"checksum,omitempty" tf:"checksum,omitempty"`

	// Labels of the resource (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Name of the cluster driver (string)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The URL to load for customized Add Clusters screen for this driver (string)
	UIURL *string `json:"uiUrl,omitempty" tf:"ui_url,omitempty"`

	// The URL to download the machine driver binary for 64-bit Linux (string)
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Domains to whitelist for the ui (list)
	WhitelistDomains []*string `json:"whitelistDomains,omitempty" tf:"whitelist_domains,omitempty"`
}

type ClusterDriverObservation struct {

	// Specify the cluster driver state (bool)
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// Actual url of the cluster driver (string)
	ActualURL *string `json:"actualUrl,omitempty" tf:"actual_url,omitempty"`

	// Annotations of the resource (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Specify whether the cluster driver is an internal cluster driver or not (bool)
	Builtin *bool `json:"builtin,omitempty" tf:"builtin,omitempty"`

	// Verify that the downloaded driver matches the expected checksum (string)
	Checksum *string `json:"checksum,omitempty" tf:"checksum,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels of the resource (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Name of the cluster driver (string)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The URL to load for customized Add Clusters screen for this driver (string)
	UIURL *string `json:"uiUrl,omitempty" tf:"ui_url,omitempty"`

	// The URL to download the machine driver binary for 64-bit Linux (string)
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Domains to whitelist for the ui (list)
	WhitelistDomains []*string `json:"whitelistDomains,omitempty" tf:"whitelist_domains,omitempty"`
}

type ClusterDriverParameters struct {

	// Specify the cluster driver state (bool)
	// +kubebuilder:validation:Optional
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// Actual url of the cluster driver (string)
	// +kubebuilder:validation:Optional
	ActualURL *string `json:"actualUrl,omitempty" tf:"actual_url,omitempty"`

	// Annotations of the resource (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Specify whether the cluster driver is an internal cluster driver or not (bool)
	// +kubebuilder:validation:Optional
	Builtin *bool `json:"builtin,omitempty" tf:"builtin,omitempty"`

	// Verify that the downloaded driver matches the expected checksum (string)
	// +kubebuilder:validation:Optional
	Checksum *string `json:"checksum,omitempty" tf:"checksum,omitempty"`

	// Labels of the resource (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Name of the cluster driver (string)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The URL to load for customized Add Clusters screen for this driver (string)
	// +kubebuilder:validation:Optional
	UIURL *string `json:"uiUrl,omitempty" tf:"ui_url,omitempty"`

	// The URL to download the machine driver binary for 64-bit Linux (string)
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Domains to whitelist for the ui (list)
	// +kubebuilder:validation:Optional
	WhitelistDomains []*string `json:"whitelistDomains,omitempty" tf:"whitelist_domains,omitempty"`
}

// ClusterDriverSpec defines the desired state of ClusterDriver
type ClusterDriverSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ClusterDriverParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClusterDriverInitParameters `json:"initProvider,omitempty"`
}

// ClusterDriverStatus defines the observed state of ClusterDriver.
type ClusterDriverStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ClusterDriverObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ClusterDriver is the Schema for the ClusterDrivers API. Provides a Rancher v2 Cluster Driver resource. This can be used to create Cluster Driver for Rancher v2.2.x Kontainer Engine clusters and retrieve their information.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rancher2}
type ClusterDriver struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.active) || (has(self.initProvider) && has(self.initProvider.active))",message="spec.forProvider.active is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.builtin) || (has(self.initProvider) && has(self.initProvider.builtin))",message="spec.forProvider.builtin is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.url) || (has(self.initProvider) && has(self.initProvider.url))",message="spec.forProvider.url is a required parameter"
	Spec   ClusterDriverSpec   `json:"spec"`
	Status ClusterDriverStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClusterDriverList contains a list of ClusterDrivers
type ClusterDriverList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClusterDriver `json:"items"`
}

// Repository type metadata.
var (
	ClusterDriver_Kind             = "ClusterDriver"
	ClusterDriver_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ClusterDriver_Kind}.String()
	ClusterDriver_KindAPIVersion   = ClusterDriver_Kind + "." + CRDGroupVersion.String()
	ClusterDriver_GroupVersionKind = CRDGroupVersion.WithKind(ClusterDriver_Kind)
)

func init() {
	SchemeBuilder.Register(&ClusterDriver{}, &ClusterDriverList{})
}
