// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ClusterRoleTemplateBindingInitParameters struct {

	// Annotations for cluster role template binding (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The cluster id where bind cluster role template binding (string)
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/cluster/rancher/v1alpha1.ClusterV2
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// The group ID to assign cluster role template binding (string)
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// The group_principal ID to assign cluster role template binding (string)
	GroupPrincipalID *string `json:"groupPrincipalId,omitempty" tf:"group_principal_id,omitempty"`

	// Labels for cluster role template binding (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the cluster role template binding (string)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The role template id from create cluster role template binding (string)
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/cluster/rancher/v1alpha1.RoleTemplate
	RoleTemplateID *string `json:"roleTemplateId,omitempty" tf:"role_template_id,omitempty"`

	// Reference to a RoleTemplate in rancher to populate roleTemplateId.
	// +kubebuilder:validation:Optional
	RoleTemplateIDRef *v1.Reference `json:"roleTemplateIdRef,omitempty" tf:"-"`

	// Selector for a RoleTemplate in rancher to populate roleTemplateId.
	// +kubebuilder:validation:Optional
	RoleTemplateIDSelector *v1.Selector `json:"roleTemplateIdSelector,omitempty" tf:"-"`

	// The user ID to assign cluster role template binding (string)
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// The user_principal ID to assign cluster role template binding (string)
	UserPrincipalID *string `json:"userPrincipalId,omitempty" tf:"user_principal_id,omitempty"`
}

type ClusterRoleTemplateBindingObservation struct {

	// Annotations for cluster role template binding (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The cluster id where bind cluster role template binding (string)
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// The group ID to assign cluster role template binding (string)
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// The group_principal ID to assign cluster role template binding (string)
	GroupPrincipalID *string `json:"groupPrincipalId,omitempty" tf:"group_principal_id,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels for cluster role template binding (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the cluster role template binding (string)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The role template id from create cluster role template binding (string)
	RoleTemplateID *string `json:"roleTemplateId,omitempty" tf:"role_template_id,omitempty"`

	// The user ID to assign cluster role template binding (string)
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// The user_principal ID to assign cluster role template binding (string)
	UserPrincipalID *string `json:"userPrincipalId,omitempty" tf:"user_principal_id,omitempty"`
}

type ClusterRoleTemplateBindingParameters struct {

	// Annotations for cluster role template binding (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The cluster id where bind cluster role template binding (string)
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/cluster/rancher/v1alpha1.ClusterV2
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// The group ID to assign cluster role template binding (string)
	// +kubebuilder:validation:Optional
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// The group_principal ID to assign cluster role template binding (string)
	// +kubebuilder:validation:Optional
	GroupPrincipalID *string `json:"groupPrincipalId,omitempty" tf:"group_principal_id,omitempty"`

	// Labels for cluster role template binding (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the cluster role template binding (string)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The role template id from create cluster role template binding (string)
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/cluster/rancher/v1alpha1.RoleTemplate
	// +kubebuilder:validation:Optional
	RoleTemplateID *string `json:"roleTemplateId,omitempty" tf:"role_template_id,omitempty"`

	// Reference to a RoleTemplate in rancher to populate roleTemplateId.
	// +kubebuilder:validation:Optional
	RoleTemplateIDRef *v1.Reference `json:"roleTemplateIdRef,omitempty" tf:"-"`

	// Selector for a RoleTemplate in rancher to populate roleTemplateId.
	// +kubebuilder:validation:Optional
	RoleTemplateIDSelector *v1.Selector `json:"roleTemplateIdSelector,omitempty" tf:"-"`

	// The user ID to assign cluster role template binding (string)
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// The user_principal ID to assign cluster role template binding (string)
	// +kubebuilder:validation:Optional
	UserPrincipalID *string `json:"userPrincipalId,omitempty" tf:"user_principal_id,omitempty"`
}

// ClusterRoleTemplateBindingSpec defines the desired state of ClusterRoleTemplateBinding
type ClusterRoleTemplateBindingSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ClusterRoleTemplateBindingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClusterRoleTemplateBindingInitParameters `json:"initProvider,omitempty"`
}

// ClusterRoleTemplateBindingStatus defines the observed state of ClusterRoleTemplateBinding.
type ClusterRoleTemplateBindingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ClusterRoleTemplateBindingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ClusterRoleTemplateBinding is the Schema for the ClusterRoleTemplateBindings API. Provides a Rancher v2 Cluster Role Template Binding resource. This can be used to create Cluster Role Template Bindings for Rancher v2 environments and retrieve their information.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rancher2}
type ClusterRoleTemplateBinding struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ClusterRoleTemplateBindingSpec   `json:"spec"`
	Status ClusterRoleTemplateBindingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClusterRoleTemplateBindingList contains a list of ClusterRoleTemplateBindings
type ClusterRoleTemplateBindingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClusterRoleTemplateBinding `json:"items"`
}

// Repository type metadata.
var (
	ClusterRoleTemplateBinding_Kind             = "ClusterRoleTemplateBinding"
	ClusterRoleTemplateBinding_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ClusterRoleTemplateBinding_Kind}.String()
	ClusterRoleTemplateBinding_KindAPIVersion   = ClusterRoleTemplateBinding_Kind + "." + CRDGroupVersion.String()
	ClusterRoleTemplateBinding_GroupVersionKind = CRDGroupVersion.WithKind(ClusterRoleTemplateBinding_Kind)
)

func init() {
	SchemeBuilder.Register(&ClusterRoleTemplateBinding{}, &ClusterRoleTemplateBindingList{})
}
