// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ClusterSyncInitParameters struct {

	// The cluster ID that is syncing (string)
	// Cluster id to sync
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/cluster/rancher/v1alpha1.ClusterV2
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// The node pool IDs used by the cluster id (list)
	// Cluster node pool ids
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/cluster/rancher/v1alpha1.NodePool
	NodePoolIds []*string `json:"nodePoolIds,omitempty" tf:"node_pool_ids,omitempty"`

	// References to NodePool in rancher to populate nodePoolIds.
	// +kubebuilder:validation:Optional
	NodePoolIdsRefs []v1.Reference `json:"nodePoolIdsRefs,omitempty" tf:"-"`

	// Selector for a list of NodePool in rancher to populate nodePoolIds.
	// +kubebuilder:validation:Optional
	NodePoolIdsSelector *v1.Selector `json:"nodePoolIdsSelector,omitempty" tf:"-"`

	// Wait until active status is confirmed a number of times (wait interval of 5s). Default: 1 means no confirmation (int)
	// Wait until active status is confirmed a number of times (wait interval of 5s)
	StateConfirm *float64 `json:"stateConfirm,omitempty" tf:"state_confirm,omitempty"`

	Synced *bool `json:"synced,omitempty" tf:"synced,omitempty"`

	// Wait until all catalogs are downloaded and active. Default: false (bool)
	// Wait until all catalogs are downloaded and active
	WaitCatalogs *bool `json:"waitCatalogs,omitempty" tf:"wait_catalogs,omitempty"`
}

type ClusterSyncNodesInitParameters struct {
}

type ClusterSyncNodesObservation struct {

	// (Computed) Annotations of the node (map).
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// (Computed) The total resources of a node (map).
	// +mapType=granular
	Capacity map[string]*string `json:"capacity,omitempty" tf:"capacity,omitempty"`

	// The cluster ID that is syncing (string)
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (Computed)  The external IP address of the node (string).
	ExternalIPAddress *string `json:"externalIpAddress,omitempty" tf:"external_ip_address,omitempty"`

	// (Computed) The hostname of the node (string).
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (Computed) The ID of the resource. Same as cluster_id (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Computed) The private IP address of the node (string).
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// (Computed) Labels of the node (map).
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Computed) The name of the node (string).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Computed) The Node Pool ID of the node (string).
	NodePoolID *string `json:"nodePoolId,omitempty" tf:"node_pool_id,omitempty"`

	// (Computed) The Node Template ID of the node (string).
	NodeTemplateID *string `json:"nodeTemplateId,omitempty" tf:"node_template_id,omitempty"`

	// (Computed) The Provider ID of the node (string).
	ProviderID *string `json:"providerId,omitempty" tf:"provider_id,omitempty"`

	// (Computed) The requested hostname (string).
	RequestedHostname *string `json:"requestedHostname,omitempty" tf:"requested_hostname,omitempty"`

	// (Computed) Roles of the node. controlplane, etcd and worker. (list)
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (Computed/Sensitive) The user to connect to the node (string).
	SSHUser *string `json:"sshUser,omitempty" tf:"ssh_user,omitempty"`

	// (Computed) General information about the node, such as kernel version, kubelet and kube-proxy version, Docker version (if used), and OS name.
	// +mapType=granular
	SystemInfo map[string]*string `json:"systemInfo,omitempty" tf:"system_info,omitempty"`
}

type ClusterSyncNodesParameters struct {
}

type ClusterSyncObservation struct {

	// The cluster ID that is syncing (string)
	// Cluster id to sync
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (Computed) Default project ID for the cluster sync (string)
	DefaultProjectID *string `json:"defaultProjectId,omitempty" tf:"default_project_id,omitempty"`

	// (Computed) The ID of the resource. Same as cluster_id (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The node pool IDs used by the cluster id (list)
	// Cluster node pool ids
	NodePoolIds []*string `json:"nodePoolIds,omitempty" tf:"node_pool_ids,omitempty"`

	// (Computed) The cluster nodes (list).
	Nodes []ClusterSyncNodesObservation `json:"nodes,omitempty" tf:"nodes,omitempty"`

	// Wait until active status is confirmed a number of times (wait interval of 5s). Default: 1 means no confirmation (int)
	// Wait until active status is confirmed a number of times (wait interval of 5s)
	StateConfirm *float64 `json:"stateConfirm,omitempty" tf:"state_confirm,omitempty"`

	Synced *bool `json:"synced,omitempty" tf:"synced,omitempty"`

	// (Computed) System project ID for the cluster sync (string)
	SystemProjectID *string `json:"systemProjectId,omitempty" tf:"system_project_id,omitempty"`

	// Wait until all catalogs are downloaded and active. Default: false (bool)
	// Wait until all catalogs are downloaded and active
	WaitCatalogs *bool `json:"waitCatalogs,omitempty" tf:"wait_catalogs,omitempty"`
}

type ClusterSyncParameters struct {

	// The cluster ID that is syncing (string)
	// Cluster id to sync
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/cluster/rancher/v1alpha1.ClusterV2
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// The node pool IDs used by the cluster id (list)
	// Cluster node pool ids
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/cluster/rancher/v1alpha1.NodePool
	// +kubebuilder:validation:Optional
	NodePoolIds []*string `json:"nodePoolIds,omitempty" tf:"node_pool_ids,omitempty"`

	// References to NodePool in rancher to populate nodePoolIds.
	// +kubebuilder:validation:Optional
	NodePoolIdsRefs []v1.Reference `json:"nodePoolIdsRefs,omitempty" tf:"-"`

	// Selector for a list of NodePool in rancher to populate nodePoolIds.
	// +kubebuilder:validation:Optional
	NodePoolIdsSelector *v1.Selector `json:"nodePoolIdsSelector,omitempty" tf:"-"`

	// Wait until active status is confirmed a number of times (wait interval of 5s). Default: 1 means no confirmation (int)
	// Wait until active status is confirmed a number of times (wait interval of 5s)
	// +kubebuilder:validation:Optional
	StateConfirm *float64 `json:"stateConfirm,omitempty" tf:"state_confirm,omitempty"`

	// +kubebuilder:validation:Optional
	Synced *bool `json:"synced,omitempty" tf:"synced,omitempty"`

	// Wait until all catalogs are downloaded and active. Default: false (bool)
	// Wait until all catalogs are downloaded and active
	// +kubebuilder:validation:Optional
	WaitCatalogs *bool `json:"waitCatalogs,omitempty" tf:"wait_catalogs,omitempty"`
}

// ClusterSyncSpec defines the desired state of ClusterSync
type ClusterSyncSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ClusterSyncParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClusterSyncInitParameters `json:"initProvider,omitempty"`
}

// ClusterSyncStatus defines the observed state of ClusterSync.
type ClusterSyncStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ClusterSyncObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ClusterSync is the Schema for the ClusterSyncs API. Provides a Rancher v2 Cluster Sync dummy resource. This can be used to create a Cluster Sync to wait for a Rancher v2 Cluster resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rancher2}
type ClusterSync struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ClusterSyncSpec   `json:"spec"`
	Status            ClusterSyncStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClusterSyncList contains a list of ClusterSyncs
type ClusterSyncList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClusterSync `json:"items"`
}

// Repository type metadata.
var (
	ClusterSync_Kind             = "ClusterSync"
	ClusterSync_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ClusterSync_Kind}.String()
	ClusterSync_KindAPIVersion   = ClusterSync_Kind + "." + CRDGroupVersion.String()
	ClusterSync_GroupVersionKind = CRDGroupVersion.WithKind(ClusterSync_Kind)
)

func init() {
	SchemeBuilder.Register(&ClusterSync{}, &ClusterSyncList{})
}
