// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type FeatureInitParameters struct {

	// Annotations for feature object (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Labels for feature object (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the feature (string)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The value of the feature. Default: false (bool)
	Value *bool `json:"value,omitempty" tf:"value,omitempty"`
}

type FeatureObservation struct {

	// Annotations for feature object (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels for feature object (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the feature (string)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The value of the feature. Default: false (bool)
	Value *bool `json:"value,omitempty" tf:"value,omitempty"`
}

type FeatureParameters struct {

	// Annotations for feature object (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Labels for feature object (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the feature (string)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The value of the feature. Default: false (bool)
	// +kubebuilder:validation:Optional
	Value *bool `json:"value,omitempty" tf:"value,omitempty"`
}

// FeatureSpec defines the desired state of Feature
type FeatureSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FeatureParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FeatureInitParameters `json:"initProvider,omitempty"`
}

// FeatureStatus defines the observed state of Feature.
type FeatureStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FeatureObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Feature is the Schema for the Features API. Provides a Rancher v2 Feature resource. This can be used to enable/disable
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rancher2}
type Feature struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   FeatureSpec   `json:"spec"`
	Status FeatureStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FeatureList contains a list of Features
type FeatureList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Feature `json:"items"`
}

// Repository type metadata.
var (
	Feature_Kind             = "Feature"
	Feature_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Feature_Kind}.String()
	Feature_KindAPIVersion   = Feature_Kind + "." + CRDGroupVersion.String()
	Feature_GroupVersionKind = CRDGroupVersion.WithKind(Feature_Kind)
)

func init() {
	SchemeBuilder.Register(&Feature{}, &FeatureList{})
}
