// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type GlobalRoleInitParameters struct {

	// Annotations for global role object (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Global role description (string)
	// Global role policy description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Names of role templates whose permissions are granted by this global role in every cluster besides the local cluster (list)
	// Names of role templates whose permissions are granted by this global role in every cluster besides the local cluster
	InheritedClusterRoles []*string `json:"inheritedClusterRoles,omitempty" tf:"inherited_cluster_roles,omitempty"`

	// Labels for global role object (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Global role name (string)
	// Global role policy name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether or not this role should be added to new users. Default false (bool)
	// Whether or not this role should be added to new users
	NewUserDefault *bool `json:"newUserDefault,omitempty" tf:"new_user_default,omitempty"`

	// Global role policy rules (list)
	// Global role policy rules
	Rules []RulesInitParameters `json:"rules,omitempty" tf:"rules,omitempty"`
}

type GlobalRoleObservation struct {

	// Annotations for global role object (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// (Computed) Builtin global role (bool)
	// Builtin global role
	Builtin *bool `json:"builtin,omitempty" tf:"builtin,omitempty"`

	// Global role description (string)
	// Global role policy description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Names of role templates whose permissions are granted by this global role in every cluster besides the local cluster (list)
	// Names of role templates whose permissions are granted by this global role in every cluster besides the local cluster
	InheritedClusterRoles []*string `json:"inheritedClusterRoles,omitempty" tf:"inherited_cluster_roles,omitempty"`

	// Labels for global role object (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Global role name (string)
	// Global role policy name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether or not this role should be added to new users. Default false (bool)
	// Whether or not this role should be added to new users
	NewUserDefault *bool `json:"newUserDefault,omitempty" tf:"new_user_default,omitempty"`

	// Global role policy rules (list)
	// Global role policy rules
	Rules []RulesObservation `json:"rules,omitempty" tf:"rules,omitempty"`

	// (Computed) The ID of the resource (string)
	// Global role uuid
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type GlobalRoleParameters struct {

	// Annotations for global role object (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Global role description (string)
	// Global role policy description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Names of role templates whose permissions are granted by this global role in every cluster besides the local cluster (list)
	// Names of role templates whose permissions are granted by this global role in every cluster besides the local cluster
	// +kubebuilder:validation:Optional
	InheritedClusterRoles []*string `json:"inheritedClusterRoles,omitempty" tf:"inherited_cluster_roles,omitempty"`

	// Labels for global role object (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Global role name (string)
	// Global role policy name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether or not this role should be added to new users. Default false (bool)
	// Whether or not this role should be added to new users
	// +kubebuilder:validation:Optional
	NewUserDefault *bool `json:"newUserDefault,omitempty" tf:"new_user_default,omitempty"`

	// Global role policy rules (list)
	// Global role policy rules
	// +kubebuilder:validation:Optional
	Rules []RulesParameters `json:"rules,omitempty" tf:"rules,omitempty"`
}

type RulesInitParameters struct {

	// Policy rule api groups (list)
	// Policy rule api groups
	APIGroups []*string `json:"apiGroups,omitempty" tf:"api_groups,omitempty"`

	// Policy rule non resource urls (list)
	// Policy rule non resource urls
	NonResourceUrls []*string `json:"nonResourceUrls,omitempty" tf:"non_resource_urls,omitempty"`

	// Policy rule resource names (list)
	// Policy rule resource names
	ResourceNames []*string `json:"resourceNames,omitempty" tf:"resource_names,omitempty"`

	// Policy rule resources (list)
	// Policy rule resources
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`

	// Policy rule verbs. bind, create, delete, deletecollection, escalate, get, impersonate, list, manage-namespaces, patch, update, updatepsa, use, view, watch, own and * values are supported (list)
	// Policy rule verbs
	Verbs []*string `json:"verbs,omitempty" tf:"verbs,omitempty"`
}

type RulesObservation struct {

	// Policy rule api groups (list)
	// Policy rule api groups
	APIGroups []*string `json:"apiGroups,omitempty" tf:"api_groups,omitempty"`

	// Policy rule non resource urls (list)
	// Policy rule non resource urls
	NonResourceUrls []*string `json:"nonResourceUrls,omitempty" tf:"non_resource_urls,omitempty"`

	// Policy rule resource names (list)
	// Policy rule resource names
	ResourceNames []*string `json:"resourceNames,omitempty" tf:"resource_names,omitempty"`

	// Policy rule resources (list)
	// Policy rule resources
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`

	// Policy rule verbs. bind, create, delete, deletecollection, escalate, get, impersonate, list, manage-namespaces, patch, update, updatepsa, use, view, watch, own and * values are supported (list)
	// Policy rule verbs
	Verbs []*string `json:"verbs,omitempty" tf:"verbs,omitempty"`
}

type RulesParameters struct {

	// Policy rule api groups (list)
	// Policy rule api groups
	// +kubebuilder:validation:Optional
	APIGroups []*string `json:"apiGroups,omitempty" tf:"api_groups,omitempty"`

	// Policy rule non resource urls (list)
	// Policy rule non resource urls
	// +kubebuilder:validation:Optional
	NonResourceUrls []*string `json:"nonResourceUrls,omitempty" tf:"non_resource_urls,omitempty"`

	// Policy rule resource names (list)
	// Policy rule resource names
	// +kubebuilder:validation:Optional
	ResourceNames []*string `json:"resourceNames,omitempty" tf:"resource_names,omitempty"`

	// Policy rule resources (list)
	// Policy rule resources
	// +kubebuilder:validation:Optional
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`

	// Policy rule verbs. bind, create, delete, deletecollection, escalate, get, impersonate, list, manage-namespaces, patch, update, updatepsa, use, view, watch, own and * values are supported (list)
	// Policy rule verbs
	// +kubebuilder:validation:Optional
	Verbs []*string `json:"verbs,omitempty" tf:"verbs,omitempty"`
}

// GlobalRoleSpec defines the desired state of GlobalRole
type GlobalRoleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     GlobalRoleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GlobalRoleInitParameters `json:"initProvider,omitempty"`
}

// GlobalRoleStatus defines the observed state of GlobalRole.
type GlobalRoleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GlobalRoleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GlobalRole is the Schema for the GlobalRoles API. Provides a Rancher v2 Global Role resource. This can be used to create Global Role for Rancher v2 and retrieve their information.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rancher2}
type GlobalRole struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   GlobalRoleSpec   `json:"spec"`
	Status GlobalRoleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GlobalRoleList contains a list of GlobalRoles
type GlobalRoleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GlobalRole `json:"items"`
}

// Repository type metadata.
var (
	GlobalRole_Kind             = "GlobalRole"
	GlobalRole_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GlobalRole_Kind}.String()
	GlobalRole_KindAPIVersion   = GlobalRole_Kind + "." + CRDGroupVersion.String()
	GlobalRole_GroupVersionKind = CRDGroupVersion.WithKind(GlobalRole_Kind)
)

func init() {
	SchemeBuilder.Register(&GlobalRole{}, &GlobalRoleList{})
}
