// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ExternalRulesInitParameters struct {

	// Policy rule api groups (list)
	// Policy rule api groups
	APIGroups []*string `json:"apiGroups,omitempty" tf:"api_groups,omitempty"`

	// Policy rule non resource urls (list)
	// Policy rule non resource urls
	NonResourceUrls []*string `json:"nonResourceUrls,omitempty" tf:"non_resource_urls,omitempty"`

	// Policy rule resource names (list)
	// Policy rule resource names
	ResourceNames []*string `json:"resourceNames,omitempty" tf:"resource_names,omitempty"`

	// Policy rule resources (list)
	// Policy rule resources
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`

	// Policy rule verbs. bind, create, delete, deletecollection, escalate, get, impersonate, list, manage-namespaces, patch, update, updatepsa, use, view, watch, own and * values are supported (list)
	// Policy rule verbs
	Verbs []*string `json:"verbs,omitempty" tf:"verbs,omitempty"`
}

type ExternalRulesObservation struct {

	// Policy rule api groups (list)
	// Policy rule api groups
	APIGroups []*string `json:"apiGroups,omitempty" tf:"api_groups,omitempty"`

	// Policy rule non resource urls (list)
	// Policy rule non resource urls
	NonResourceUrls []*string `json:"nonResourceUrls,omitempty" tf:"non_resource_urls,omitempty"`

	// Policy rule resource names (list)
	// Policy rule resource names
	ResourceNames []*string `json:"resourceNames,omitempty" tf:"resource_names,omitempty"`

	// Policy rule resources (list)
	// Policy rule resources
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`

	// Policy rule verbs. bind, create, delete, deletecollection, escalate, get, impersonate, list, manage-namespaces, patch, update, updatepsa, use, view, watch, own and * values are supported (list)
	// Policy rule verbs
	Verbs []*string `json:"verbs,omitempty" tf:"verbs,omitempty"`
}

type ExternalRulesParameters struct {

	// Policy rule api groups (list)
	// Policy rule api groups
	// +kubebuilder:validation:Optional
	APIGroups []*string `json:"apiGroups,omitempty" tf:"api_groups,omitempty"`

	// Policy rule non resource urls (list)
	// Policy rule non resource urls
	// +kubebuilder:validation:Optional
	NonResourceUrls []*string `json:"nonResourceUrls,omitempty" tf:"non_resource_urls,omitempty"`

	// Policy rule resource names (list)
	// Policy rule resource names
	// +kubebuilder:validation:Optional
	ResourceNames []*string `json:"resourceNames,omitempty" tf:"resource_names,omitempty"`

	// Policy rule resources (list)
	// Policy rule resources
	// +kubebuilder:validation:Optional
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`

	// Policy rule verbs. bind, create, delete, deletecollection, escalate, get, impersonate, list, manage-namespaces, patch, update, updatepsa, use, view, watch, own and * values are supported (list)
	// Policy rule verbs
	// +kubebuilder:validation:Optional
	Verbs []*string `json:"verbs,omitempty" tf:"verbs,omitempty"`
}

type RoleTemplateInitParameters struct {

	// Administrative role template. Default false (bool)
	// Administrative role template
	Administrative *bool `json:"administrative,omitempty" tf:"administrative,omitempty"`

	// Annotations for role template object (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Role template context. cluster and project values are supported. Default: cluster (string)
	// Context role template
	Context *string `json:"context,omitempty" tf:"context,omitempty"`

	// Default role template for new created cluster or project. Default false (bool)
	// Default role template for new created cluster or project
	DefaultRole *bool `json:"defaultRole,omitempty" tf:"default_role,omitempty"`

	// Role template description (string)
	// Role template policy description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// External role template. Default false (bool)
	// External role template
	External *bool `json:"external,omitempty" tf:"external,omitempty"`

	// External rules used for authorization. This field is required when external=true and no underlying ClusterRole exists. (list)
	// External policy rules used for authorization
	ExternalRules []ExternalRulesInitParameters `json:"externalRules,omitempty" tf:"external_rules,omitempty"`

	// Hidden role template. Default false (bool)
	// Hidden role template
	Hidden *bool `json:"hidden,omitempty" tf:"hidden,omitempty"`

	// Labels for role template object (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Locked role template. Default false (bool)
	// Locked role template
	Locked *bool `json:"locked,omitempty" tf:"locked,omitempty"`

	// Role template name (string)
	// Role template policy name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Inherit role template IDs (list)
	// Inherit role template IDs
	RoleTemplateIds []*string `json:"roleTemplateIds,omitempty" tf:"role_template_ids,omitempty"`

	// Role template policy rules (list)
	// Role template policy rules
	Rules []RoleTemplateRulesInitParameters `json:"rules,omitempty" tf:"rules,omitempty"`
}

type RoleTemplateObservation struct {

	// Administrative role template. Default false (bool)
	// Administrative role template
	Administrative *bool `json:"administrative,omitempty" tf:"administrative,omitempty"`

	// Annotations for role template object (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// (Computed) Builtin role template (string)
	// Builtin role template
	Builtin *bool `json:"builtin,omitempty" tf:"builtin,omitempty"`

	// Role template context. cluster and project values are supported. Default: cluster (string)
	// Context role template
	Context *string `json:"context,omitempty" tf:"context,omitempty"`

	// Default role template for new created cluster or project. Default false (bool)
	// Default role template for new created cluster or project
	DefaultRole *bool `json:"defaultRole,omitempty" tf:"default_role,omitempty"`

	// Role template description (string)
	// Role template policy description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// External role template. Default false (bool)
	// External role template
	External *bool `json:"external,omitempty" tf:"external,omitempty"`

	// External rules used for authorization. This field is required when external=true and no underlying ClusterRole exists. (list)
	// External policy rules used for authorization
	ExternalRules []ExternalRulesObservation `json:"externalRules,omitempty" tf:"external_rules,omitempty"`

	// Hidden role template. Default false (bool)
	// Hidden role template
	Hidden *bool `json:"hidden,omitempty" tf:"hidden,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels for role template object (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Locked role template. Default false (bool)
	// Locked role template
	Locked *bool `json:"locked,omitempty" tf:"locked,omitempty"`

	// Role template name (string)
	// Role template policy name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Inherit role template IDs (list)
	// Inherit role template IDs
	RoleTemplateIds []*string `json:"roleTemplateIds,omitempty" tf:"role_template_ids,omitempty"`

	// Role template policy rules (list)
	// Role template policy rules
	Rules []RoleTemplateRulesObservation `json:"rules,omitempty" tf:"rules,omitempty"`
}

type RoleTemplateParameters struct {

	// Administrative role template. Default false (bool)
	// Administrative role template
	// +kubebuilder:validation:Optional
	Administrative *bool `json:"administrative,omitempty" tf:"administrative,omitempty"`

	// Annotations for role template object (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Role template context. cluster and project values are supported. Default: cluster (string)
	// Context role template
	// +kubebuilder:validation:Optional
	Context *string `json:"context,omitempty" tf:"context,omitempty"`

	// Default role template for new created cluster or project. Default false (bool)
	// Default role template for new created cluster or project
	// +kubebuilder:validation:Optional
	DefaultRole *bool `json:"defaultRole,omitempty" tf:"default_role,omitempty"`

	// Role template description (string)
	// Role template policy description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// External role template. Default false (bool)
	// External role template
	// +kubebuilder:validation:Optional
	External *bool `json:"external,omitempty" tf:"external,omitempty"`

	// External rules used for authorization. This field is required when external=true and no underlying ClusterRole exists. (list)
	// External policy rules used for authorization
	// +kubebuilder:validation:Optional
	ExternalRules []ExternalRulesParameters `json:"externalRules,omitempty" tf:"external_rules,omitempty"`

	// Hidden role template. Default false (bool)
	// Hidden role template
	// +kubebuilder:validation:Optional
	Hidden *bool `json:"hidden,omitempty" tf:"hidden,omitempty"`

	// Labels for role template object (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Locked role template. Default false (bool)
	// Locked role template
	// +kubebuilder:validation:Optional
	Locked *bool `json:"locked,omitempty" tf:"locked,omitempty"`

	// Role template name (string)
	// Role template policy name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Inherit role template IDs (list)
	// Inherit role template IDs
	// +kubebuilder:validation:Optional
	RoleTemplateIds []*string `json:"roleTemplateIds,omitempty" tf:"role_template_ids,omitempty"`

	// Role template policy rules (list)
	// Role template policy rules
	// +kubebuilder:validation:Optional
	Rules []RoleTemplateRulesParameters `json:"rules,omitempty" tf:"rules,omitempty"`
}

type RoleTemplateRulesInitParameters struct {

	// Policy rule api groups (list)
	// Policy rule api groups
	APIGroups []*string `json:"apiGroups,omitempty" tf:"api_groups,omitempty"`

	// Policy rule non resource urls (list)
	// Policy rule non resource urls
	NonResourceUrls []*string `json:"nonResourceUrls,omitempty" tf:"non_resource_urls,omitempty"`

	// Policy rule resource names (list)
	// Policy rule resource names
	ResourceNames []*string `json:"resourceNames,omitempty" tf:"resource_names,omitempty"`

	// Policy rule resources (list)
	// Policy rule resources
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`

	// Policy rule verbs. bind, create, delete, deletecollection, escalate, get, impersonate, list, manage-namespaces, patch, update, updatepsa, use, view, watch, own and * values are supported (list)
	// Policy rule verbs
	Verbs []*string `json:"verbs,omitempty" tf:"verbs,omitempty"`
}

type RoleTemplateRulesObservation struct {

	// Policy rule api groups (list)
	// Policy rule api groups
	APIGroups []*string `json:"apiGroups,omitempty" tf:"api_groups,omitempty"`

	// Policy rule non resource urls (list)
	// Policy rule non resource urls
	NonResourceUrls []*string `json:"nonResourceUrls,omitempty" tf:"non_resource_urls,omitempty"`

	// Policy rule resource names (list)
	// Policy rule resource names
	ResourceNames []*string `json:"resourceNames,omitempty" tf:"resource_names,omitempty"`

	// Policy rule resources (list)
	// Policy rule resources
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`

	// Policy rule verbs. bind, create, delete, deletecollection, escalate, get, impersonate, list, manage-namespaces, patch, update, updatepsa, use, view, watch, own and * values are supported (list)
	// Policy rule verbs
	Verbs []*string `json:"verbs,omitempty" tf:"verbs,omitempty"`
}

type RoleTemplateRulesParameters struct {

	// Policy rule api groups (list)
	// Policy rule api groups
	// +kubebuilder:validation:Optional
	APIGroups []*string `json:"apiGroups,omitempty" tf:"api_groups,omitempty"`

	// Policy rule non resource urls (list)
	// Policy rule non resource urls
	// +kubebuilder:validation:Optional
	NonResourceUrls []*string `json:"nonResourceUrls,omitempty" tf:"non_resource_urls,omitempty"`

	// Policy rule resource names (list)
	// Policy rule resource names
	// +kubebuilder:validation:Optional
	ResourceNames []*string `json:"resourceNames,omitempty" tf:"resource_names,omitempty"`

	// Policy rule resources (list)
	// Policy rule resources
	// +kubebuilder:validation:Optional
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`

	// Policy rule verbs. bind, create, delete, deletecollection, escalate, get, impersonate, list, manage-namespaces, patch, update, updatepsa, use, view, watch, own and * values are supported (list)
	// Policy rule verbs
	// +kubebuilder:validation:Optional
	Verbs []*string `json:"verbs,omitempty" tf:"verbs,omitempty"`
}

// RoleTemplateSpec defines the desired state of RoleTemplate
type RoleTemplateSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RoleTemplateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RoleTemplateInitParameters `json:"initProvider,omitempty"`
}

// RoleTemplateStatus defines the observed state of RoleTemplate.
type RoleTemplateStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RoleTemplateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RoleTemplate is the Schema for the RoleTemplates API. Provides a Rancher v2 Role Template resource. This can be used to create Role Template for Rancher v2 and retrieve their information.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rancher2}
type RoleTemplate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   RoleTemplateSpec   `json:"spec"`
	Status RoleTemplateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RoleTemplateList contains a list of RoleTemplates
type RoleTemplateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RoleTemplate `json:"items"`
}

// Repository type metadata.
var (
	RoleTemplate_Kind             = "RoleTemplate"
	RoleTemplate_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RoleTemplate_Kind}.String()
	RoleTemplate_KindAPIVersion   = RoleTemplate_Kind + "." + CRDGroupVersion.String()
	RoleTemplate_GroupVersionKind = CRDGroupVersion.WithKind(RoleTemplate_Kind)
)

func init() {
	SchemeBuilder.Register(&RoleTemplate{}, &RoleTemplateList{})
}
