// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type TokenInitParameters struct {

	// (Computed) Annotations of the token (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// should be provided).
	// Cluster ID for scoped token
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/cluster/rancher/v1alpha1.ClusterV2
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// Token description (string)
	// Token description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Computed) Labels of the token (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Renew token if expired or disabled. If false, the token will not be renewed. Default true (bool)
	// Renew expired or disabled token
	Renew *bool `json:"renew,omitempty" tf:"renew,omitempty"`

	// Token time to live in seconds. Default 0 (int)
	// Token time to live in seconds
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

type TokenObservation struct {

	// (Computed) Token access key part (string)
	// Token access key
	AccessKey *string `json:"accessKey,omitempty" tf:"access_key,omitempty"`

	// (Computed) Annotations of the token (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// should be provided).
	// Cluster ID for scoped token
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Token description (string)
	// Token description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Computed) Token is enabled (bool)
	// Token enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Computed) Token is expired (bool)
	// Token expired
	Expired *bool `json:"expired,omitempty" tf:"expired,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Computed) Labels of the token (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Computed) Token name (string)
	// Token name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Renew token if expired or disabled. If false, the token will not be renewed. Default true (bool)
	// Renew expired or disabled token
	Renew *bool `json:"renew,omitempty" tf:"renew,omitempty"`

	// Token time to live in seconds. Default 0 (int)
	// Token time to live in seconds
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// (Computed) Token user ID (string)
	// Token user ID
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type TokenParameters struct {

	// (Computed) Annotations of the token (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// should be provided).
	// Cluster ID for scoped token
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/cluster/rancher/v1alpha1.ClusterV2
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// Token description (string)
	// Token description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Computed) Labels of the token (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Renew token if expired or disabled. If false, the token will not be renewed. Default true (bool)
	// Renew expired or disabled token
	// +kubebuilder:validation:Optional
	Renew *bool `json:"renew,omitempty" tf:"renew,omitempty"`

	// Token time to live in seconds. Default 0 (int)
	// Token time to live in seconds
	// +kubebuilder:validation:Optional
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

// TokenSpec defines the desired state of Token
type TokenSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TokenParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TokenInitParameters `json:"initProvider,omitempty"`
}

// TokenStatus defines the observed state of Token.
type TokenStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TokenObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Token is the Schema for the Tokens API. Provides a Rancher v2 Token resource. This can be used to create Tokens for Rancher v2 provider user and retrieve their information.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,rancher2}
type Token struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TokenSpec   `json:"spec"`
	Status            TokenStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TokenList contains a list of Tokens
type TokenList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Token `json:"items"`
}

// Repository type metadata.
var (
	Token_Kind             = "Token"
	Token_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Token_Kind}.String()
	Token_KindAPIVersion   = Token_Kind + "." + CRDGroupVersion.String()
	Token_GroupVersionKind = CRDGroupVersion.WithKind(Token_Kind)
)

func init() {
	SchemeBuilder.Register(&Token{}, &TokenList{})
}
