apiVersion: rancher.rancher2.m.contrib.crossplane.io/v1alpha1
kind: CloudCredential
metadata:
  annotations:
    meta.upbound.io/example-id: rancher/v1alpha1/cloudcredential
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: crossplane-system
spec:
  forProvider:
    amazonec2CredentialConfig:
    - accessKeySecretRef:
        key: example-key
        name: example-secret
      secretKeySecretRef:
        key: example-key
        name: example-secret
    description: foo test
    name: foo
