apiVersion: rancher.rancher2.m.contrib.crossplane.io/v1alpha1
kind: ClusterSync
metadata:
  annotations:
    meta.upbound.io/example-id: rancher/v1alpha1/clustersync
  labels:
    testing.upbound.io/example-name: foo-custom
  name: foo-custom
  namespace: crossplane-system
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo-custom
    nodePoolIdsRefs:
    - name: foo

---

apiVersion: rancher.rancher2.m.contrib.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: rancher/v1alpha1/clustersync
  labels:
    testing.upbound.io/example-name: foo-custom
  name: foo-custom
  namespace: crossplane-system
spec:
  forProvider:
    description: Foo rancher2 custom cluster
    name: foo-custom
    rkeConfig:
    - network:
      - plugin: canal

---

apiVersion: rancher.rancher2.m.contrib.crossplane.io/v1alpha1
kind: NodePool
metadata:
  annotations:
    meta.upbound.io/example-id: rancher/v1alpha1/clustersync
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: crossplane-system
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo-custom
    controlPlane: true
    etcd: true
    hostnamePrefix: foo-cluster-0
    name: foo
    nodeTemplateId: ${rancher2_node_template.foo.id}
    quantity: 3
    worker: true

---

apiVersion: k8s.rancher2.m.contrib.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: rancher/v1alpha1/clustersync
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: crossplane-system
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo-custom
    containerResourceLimit:
    - limitsCpu: 20m
      limitsMemory: 20Mi
      requestsCpu: 1m
      requestsMemory: 1Mi
    description: Terraform namespace acceptance test
    name: foo
    resourceQuota:
    - namespaceDefaultLimit:
      - limitsCpu: 500m
        limitsMemory: 500Mi
        requestsStorage: 1Gi
      projectLimit:
      - limitsCpu: 2000m
        limitsMemory: 2000Mi
        requestsStorage: 2Gi
