apiVersion: rancher.rancher2.m.contrib.crossplane.io/v1alpha1
kind: GlobalRole
metadata:
  annotations:
    meta.upbound.io/example-id: rancher/v1alpha1/globalrole
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: crossplane-system
spec:
  forProvider:
    description: Terraform global role acceptance test
    name: foo
    newUserDefault: true
    rules:
    - apiGroups:
      - '*'
      resources:
      - secrets
      verbs:
      - create
