apiVersion: rancher.rancher2.m.contrib.crossplane.io/v1alpha1
kind: RoleTemplate
metadata:
  annotations:
    meta.upbound.io/example-id: rancher/v1alpha1/roletemplate
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: crossplane-system
spec:
  forProvider:
    context: cluster
    defaultRole: true
    description: Terraform role template acceptance test
    name: foo
    rules:
    - apiGroups:
      - '*'
      resources:
      - secrets
      verbs:
      - create
