// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package namespaced contains Kubernetes API for the provider.
package namespaced

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/disaster37/provider-rancher2/apis/namespaced/app/v1alpha1"
	v1alpha1auth "github.com/disaster37/provider-rancher2/apis/namespaced/auth/v1alpha1"
	v1alpha1k8s "github.com/disaster37/provider-rancher2/apis/namespaced/k8s/v1alpha1"
	v1alpha1rancher "github.com/disaster37/provider-rancher2/apis/namespaced/rancher/v1alpha1"
	v1alpha1rbac "github.com/disaster37/provider-rancher2/apis/namespaced/rbac/v1alpha1"
	v1alpha1namespaced "github.com/disaster37/provider-rancher2/apis/namespaced/v1alpha1"
	v1beta1 "github.com/disaster37/provider-rancher2/apis/namespaced/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1auth.SchemeBuilder.AddToScheme,
		v1alpha1k8s.SchemeBuilder.AddToScheme,
		v1alpha1rancher.SchemeBuilder.AddToScheme,
		v1alpha1rbac.SchemeBuilder.AddToScheme,
		v1alpha1namespaced.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
