// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type Amazonec2CredentialConfigInitParameters struct {

	// AWS access key (string)
	// AWS Access Key
	AccessKeySecretRef v1.LocalSecretKeySelector `json:"accessKeySecretRef" tf:"-"`

	// AWS default region (string)
	// AWS default region
	DefaultRegion *string `json:"defaultRegion,omitempty" tf:"default_region,omitempty"`

	// AWS secret key (string)
	// AWS Secret Key
	SecretKeySecretRef v1.LocalSecretKeySelector `json:"secretKeySecretRef" tf:"-"`
}

type Amazonec2CredentialConfigObservation struct {

	// AWS default region (string)
	// AWS default region
	DefaultRegion *string `json:"defaultRegion,omitempty" tf:"default_region,omitempty"`
}

type Amazonec2CredentialConfigParameters struct {

	// AWS access key (string)
	// AWS Access Key
	// +kubebuilder:validation:Optional
	AccessKeySecretRef v1.LocalSecretKeySelector `json:"accessKeySecretRef" tf:"-"`

	// AWS default region (string)
	// AWS default region
	// +kubebuilder:validation:Optional
	DefaultRegion *string `json:"defaultRegion,omitempty" tf:"default_region,omitempty"`

	// AWS secret key (string)
	// AWS Secret Key
	// +kubebuilder:validation:Optional
	SecretKeySecretRef v1.LocalSecretKeySelector `json:"secretKeySecretRef" tf:"-"`
}

type AzureCredentialConfigInitParameters struct {

	// Azure Service Principal Account ID (string)
	// Azure Service Principal Account ID
	ClientIDSecretRef v1.LocalSecretKeySelector `json:"clientIdSecretRef" tf:"-"`

	// Azure Service Principal Account password (string)
	// Azure Service Principal Account password
	ClientSecretSecretRef v1.LocalSecretKeySelector `json:"clientSecretSecretRef" tf:"-"`

	// Azure environment (e.g. AzurePublicCloud, AzureChinaCloud) (string)
	// Azure environment (e.g. AzurePublicCloud, AzureChinaCloud)
	Environment *string `json:"environment,omitempty" tf:"environment,omitempty"`

	// Azure Subscription ID (string)
	// Azure Subscription ID
	SubscriptionIDSecretRef v1.LocalSecretKeySelector `json:"subscriptionIdSecretRef" tf:"-"`

	// Azure Tenant ID (string)
	// Azure Tenant ID
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`
}

type AzureCredentialConfigObservation struct {

	// Azure environment (e.g. AzurePublicCloud, AzureChinaCloud) (string)
	// Azure environment (e.g. AzurePublicCloud, AzureChinaCloud)
	Environment *string `json:"environment,omitempty" tf:"environment,omitempty"`

	// Azure Tenant ID (string)
	// Azure Tenant ID
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`
}

type AzureCredentialConfigParameters struct {

	// Azure Service Principal Account ID (string)
	// Azure Service Principal Account ID
	// +kubebuilder:validation:Optional
	ClientIDSecretRef v1.LocalSecretKeySelector `json:"clientIdSecretRef" tf:"-"`

	// Azure Service Principal Account password (string)
	// Azure Service Principal Account password
	// +kubebuilder:validation:Optional
	ClientSecretSecretRef v1.LocalSecretKeySelector `json:"clientSecretSecretRef" tf:"-"`

	// Azure environment (e.g. AzurePublicCloud, AzureChinaCloud) (string)
	// Azure environment (e.g. AzurePublicCloud, AzureChinaCloud)
	// +kubebuilder:validation:Optional
	Environment *string `json:"environment,omitempty" tf:"environment,omitempty"`

	// Azure Subscription ID (string)
	// Azure Subscription ID
	// +kubebuilder:validation:Optional
	SubscriptionIDSecretRef v1.LocalSecretKeySelector `json:"subscriptionIdSecretRef" tf:"-"`

	// Azure Tenant ID (string)
	// Azure Tenant ID
	// +kubebuilder:validation:Optional
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`
}

type CloudCredentialInitParameters struct {

	// AWS config for the Cloud Credential (list maxitems:1)
	Amazonec2CredentialConfig []Amazonec2CredentialConfigInitParameters `json:"amazonec2CredentialConfig,omitempty" tf:"amazonec2_credential_config,omitempty"`

	// Annotations for Cloud Credential object (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Azure config for the Cloud Credential (list maxitems:1)
	AzureCredentialConfig []AzureCredentialConfigInitParameters `json:"azureCredentialConfig,omitempty" tf:"azure_credential_config,omitempty"`

	// Description for the Cloud Credential (string)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// DigitalOcean config for the Cloud Credential (list maxitems:1)
	DigitaloceanCredentialConfig []DigitaloceanCredentialConfigInitParameters `json:"digitaloceanCredentialConfig,omitempty" tf:"digitalocean_credential_config,omitempty"`

	// Google config for the Cloud Credential (list maxitems:1)
	GoogleCredentialConfig []GoogleCredentialConfigInitParameters `json:"googleCredentialConfig,omitempty" tf:"google_credential_config,omitempty"`

	// Harvester config for the Cloud Credential (list maxitems:1)
	HarvesterCredentialConfig []HarvesterCredentialConfigInitParameters `json:"harvesterCredentialConfig,omitempty" tf:"harvester_credential_config,omitempty"`

	// Labels for Cloud Credential object (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Linode config for the Cloud Credential (list maxitems:1)
	LinodeCredentialConfig []LinodeCredentialConfigInitParameters `json:"linodeCredentialConfig,omitempty" tf:"linode_credential_config,omitempty"`

	// The name of the Cloud Credential (string)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// OpenStack config for the Cloud Credential (list maxitems:1)
	OpenstackCredentialConfig []OpenstackCredentialConfigInitParameters `json:"openstackCredentialConfig,omitempty" tf:"openstack_credential_config,omitempty"`

	// S3 config for the Cloud Credential. For Rancher 2.6.0 and above (list maxitems:1)
	S3CredentialConfig []S3CredentialConfigInitParameters `json:"s3CredentialConfig,omitempty" tf:"s3_credential_config,omitempty"`

	// vSphere config for the Cloud Credential (list maxitems:1)
	VsphereCredentialConfig []VsphereCredentialConfigInitParameters `json:"vsphereCredentialConfig,omitempty" tf:"vsphere_credential_config,omitempty"`
}

type CloudCredentialObservation struct {

	// AWS config for the Cloud Credential (list maxitems:1)
	Amazonec2CredentialConfig []Amazonec2CredentialConfigObservation `json:"amazonec2CredentialConfig,omitempty" tf:"amazonec2_credential_config,omitempty"`

	// Annotations for Cloud Credential object (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Azure config for the Cloud Credential (list maxitems:1)
	AzureCredentialConfig []AzureCredentialConfigObservation `json:"azureCredentialConfig,omitempty" tf:"azure_credential_config,omitempty"`

	// Description for the Cloud Credential (string)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// DigitalOcean config for the Cloud Credential (list maxitems:1)
	DigitaloceanCredentialConfig []DigitaloceanCredentialConfigParameters `json:"digitaloceanCredentialConfig,omitempty" tf:"digitalocean_credential_config,omitempty"`

	// (Computed) The driver of the Cloud Credential (string)
	Driver *string `json:"driver,omitempty" tf:"driver,omitempty"`

	// Google config for the Cloud Credential (list maxitems:1)
	GoogleCredentialConfig []GoogleCredentialConfigParameters `json:"googleCredentialConfig,omitempty" tf:"google_credential_config,omitempty"`

	// Harvester config for the Cloud Credential (list maxitems:1)
	HarvesterCredentialConfig []HarvesterCredentialConfigObservation `json:"harvesterCredentialConfig,omitempty" tf:"harvester_credential_config,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels for Cloud Credential object (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Linode config for the Cloud Credential (list maxitems:1)
	LinodeCredentialConfig []LinodeCredentialConfigParameters `json:"linodeCredentialConfig,omitempty" tf:"linode_credential_config,omitempty"`

	// The name of the Cloud Credential (string)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// OpenStack config for the Cloud Credential (list maxitems:1)
	OpenstackCredentialConfig []OpenstackCredentialConfigParameters `json:"openstackCredentialConfig,omitempty" tf:"openstack_credential_config,omitempty"`

	// S3 config for the Cloud Credential. For Rancher 2.6.0 and above (list maxitems:1)
	S3CredentialConfig []S3CredentialConfigObservation `json:"s3CredentialConfig,omitempty" tf:"s3_credential_config,omitempty"`

	// vSphere config for the Cloud Credential (list maxitems:1)
	VsphereCredentialConfig []VsphereCredentialConfigObservation `json:"vsphereCredentialConfig,omitempty" tf:"vsphere_credential_config,omitempty"`
}

type CloudCredentialParameters struct {

	// AWS config for the Cloud Credential (list maxitems:1)
	// +kubebuilder:validation:Optional
	Amazonec2CredentialConfig []Amazonec2CredentialConfigParameters `json:"amazonec2CredentialConfig,omitempty" tf:"amazonec2_credential_config,omitempty"`

	// Annotations for Cloud Credential object (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Azure config for the Cloud Credential (list maxitems:1)
	// +kubebuilder:validation:Optional
	AzureCredentialConfig []AzureCredentialConfigParameters `json:"azureCredentialConfig,omitempty" tf:"azure_credential_config,omitempty"`

	// Description for the Cloud Credential (string)
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// DigitalOcean config for the Cloud Credential (list maxitems:1)
	// +kubebuilder:validation:Optional
	DigitaloceanCredentialConfig []DigitaloceanCredentialConfigParameters `json:"digitaloceanCredentialConfig,omitempty" tf:"digitalocean_credential_config,omitempty"`

	// Google config for the Cloud Credential (list maxitems:1)
	// +kubebuilder:validation:Optional
	GoogleCredentialConfig []GoogleCredentialConfigParameters `json:"googleCredentialConfig,omitempty" tf:"google_credential_config,omitempty"`

	// Harvester config for the Cloud Credential (list maxitems:1)
	// +kubebuilder:validation:Optional
	HarvesterCredentialConfig []HarvesterCredentialConfigParameters `json:"harvesterCredentialConfig,omitempty" tf:"harvester_credential_config,omitempty"`

	// Labels for Cloud Credential object (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Linode config for the Cloud Credential (list maxitems:1)
	// +kubebuilder:validation:Optional
	LinodeCredentialConfig []LinodeCredentialConfigParameters `json:"linodeCredentialConfig,omitempty" tf:"linode_credential_config,omitempty"`

	// The name of the Cloud Credential (string)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// OpenStack config for the Cloud Credential (list maxitems:1)
	// +kubebuilder:validation:Optional
	OpenstackCredentialConfig []OpenstackCredentialConfigParameters `json:"openstackCredentialConfig,omitempty" tf:"openstack_credential_config,omitempty"`

	// S3 config for the Cloud Credential. For Rancher 2.6.0 and above (list maxitems:1)
	// +kubebuilder:validation:Optional
	S3CredentialConfig []S3CredentialConfigParameters `json:"s3CredentialConfig,omitempty" tf:"s3_credential_config,omitempty"`

	// vSphere config for the Cloud Credential (list maxitems:1)
	// +kubebuilder:validation:Optional
	VsphereCredentialConfig []VsphereCredentialConfigParameters `json:"vsphereCredentialConfig,omitempty" tf:"vsphere_credential_config,omitempty"`
}

type DigitaloceanCredentialConfigInitParameters struct {

	// DigitalOcean access token (string)
	// Digital Ocean access token
	AccessTokenSecretRef v1.LocalSecretKeySelector `json:"accessTokenSecretRef" tf:"-"`
}

type DigitaloceanCredentialConfigObservation struct {
}

type DigitaloceanCredentialConfigParameters struct {

	// DigitalOcean access token (string)
	// Digital Ocean access token
	// +kubebuilder:validation:Optional
	AccessTokenSecretRef v1.LocalSecretKeySelector `json:"accessTokenSecretRef" tf:"-"`
}

type GoogleCredentialConfigInitParameters struct {

	// Google auth encoded json (string)
	// Google auth encoded json
	AuthEncodedJSONSecretRef v1.LocalSecretKeySelector `json:"authEncodedJsonSecretRef" tf:"-"`
}

type GoogleCredentialConfigObservation struct {
}

type GoogleCredentialConfigParameters struct {

	// Google auth encoded json (string)
	// Google auth encoded json
	// +kubebuilder:validation:Optional
	AuthEncodedJSONSecretRef v1.LocalSecretKeySelector `json:"authEncodedJsonSecretRef" tf:"-"`
}

type HarvesterCredentialConfigInitParameters struct {

	// Imported Harvester Cluster ID (string)
	// The cluster id of imported Harvester cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Harvester Cluster Type. Supported values : "imported" | "external" (string)
	// Harvester cluster type. must be imported or external
	ClusterType *string `json:"clusterType,omitempty" tf:"cluster_type,omitempty"`

	// Harvester Cluster KubeConfig Content (string)
	// Harvester cluster kubeconfig content
	KubeconfigContentSecretRef v1.LocalSecretKeySelector `json:"kubeconfigContentSecretRef" tf:"-"`
}

type HarvesterCredentialConfigObservation struct {

	// Imported Harvester Cluster ID (string)
	// The cluster id of imported Harvester cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Harvester Cluster Type. Supported values : "imported" | "external" (string)
	// Harvester cluster type. must be imported or external
	ClusterType *string `json:"clusterType,omitempty" tf:"cluster_type,omitempty"`
}

type HarvesterCredentialConfigParameters struct {

	// Imported Harvester Cluster ID (string)
	// The cluster id of imported Harvester cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Harvester Cluster Type. Supported values : "imported" | "external" (string)
	// Harvester cluster type. must be imported or external
	// +kubebuilder:validation:Optional
	ClusterType *string `json:"clusterType" tf:"cluster_type,omitempty"`

	// Harvester Cluster KubeConfig Content (string)
	// Harvester cluster kubeconfig content
	// +kubebuilder:validation:Optional
	KubeconfigContentSecretRef v1.LocalSecretKeySelector `json:"kubeconfigContentSecretRef" tf:"-"`
}

type LinodeCredentialConfigInitParameters struct {

	// Linode API token (string)
	// Linode API token
	TokenSecretRef v1.LocalSecretKeySelector `json:"tokenSecretRef" tf:"-"`
}

type LinodeCredentialConfigObservation struct {
}

type LinodeCredentialConfigParameters struct {

	// Linode API token (string)
	// Linode API token
	// +kubebuilder:validation:Optional
	TokenSecretRef v1.LocalSecretKeySelector `json:"tokenSecretRef" tf:"-"`
}

type OpenstackCredentialConfigInitParameters struct {

	// OpenStack password (string)
	// OpenStack password
	PasswordSecretRef v1.LocalSecretKeySelector `json:"passwordSecretRef" tf:"-"`
}

type OpenstackCredentialConfigObservation struct {
}

type OpenstackCredentialConfigParameters struct {

	// OpenStack password (string)
	// OpenStack password
	// +kubebuilder:validation:Optional
	PasswordSecretRef v1.LocalSecretKeySelector `json:"passwordSecretRef" tf:"-"`
}

type S3CredentialConfigInitParameters struct {

	// AWS access key (string)
	// AWS Access Key
	AccessKeySecretRef v1.LocalSecretKeySelector `json:"accessKeySecretRef" tf:"-"`

	// AWS default bucket (string)
	// AWS default bucket
	DefaultBucket *string `json:"defaultBucket,omitempty" tf:"default_bucket,omitempty"`

	// AWS default endpoint (string)
	// AWS default endpoint
	DefaultEndpoint *string `json:"defaultEndpoint,omitempty" tf:"default_endpoint,omitempty"`

	// AWS default endpoint CA (string)
	// AWS default endpoint CA
	DefaultEndpointCASecretRef *v1.LocalSecretKeySelector `json:"defaultEndpointCaSecretRef,omitempty" tf:"-"`

	// AWS default folder (string)
	// AWS default folder
	DefaultFolder *string `json:"defaultFolder,omitempty" tf:"default_folder,omitempty"`

	// AWS default region (string)
	// AWS default region
	DefaultRegion *string `json:"defaultRegion,omitempty" tf:"default_region,omitempty"`

	// AWS default skip ssl verify. Default: false (bool)
	// AWS default skip ssl verify
	DefaultSkipSSLVerify *bool `json:"defaultSkipSslVerify,omitempty" tf:"default_skip_ssl_verify,omitempty"`

	// AWS secret key (string)
	// AWS Secret Key
	SecretKeySecretRef v1.LocalSecretKeySelector `json:"secretKeySecretRef" tf:"-"`
}

type S3CredentialConfigObservation struct {

	// AWS default bucket (string)
	// AWS default bucket
	DefaultBucket *string `json:"defaultBucket,omitempty" tf:"default_bucket,omitempty"`

	// AWS default endpoint (string)
	// AWS default endpoint
	DefaultEndpoint *string `json:"defaultEndpoint,omitempty" tf:"default_endpoint,omitempty"`

	// AWS default folder (string)
	// AWS default folder
	DefaultFolder *string `json:"defaultFolder,omitempty" tf:"default_folder,omitempty"`

	// AWS default region (string)
	// AWS default region
	DefaultRegion *string `json:"defaultRegion,omitempty" tf:"default_region,omitempty"`

	// AWS default skip ssl verify. Default: false (bool)
	// AWS default skip ssl verify
	DefaultSkipSSLVerify *bool `json:"defaultSkipSslVerify,omitempty" tf:"default_skip_ssl_verify,omitempty"`
}

type S3CredentialConfigParameters struct {

	// AWS access key (string)
	// AWS Access Key
	// +kubebuilder:validation:Optional
	AccessKeySecretRef v1.LocalSecretKeySelector `json:"accessKeySecretRef" tf:"-"`

	// AWS default bucket (string)
	// AWS default bucket
	// +kubebuilder:validation:Optional
	DefaultBucket *string `json:"defaultBucket,omitempty" tf:"default_bucket,omitempty"`

	// AWS default endpoint (string)
	// AWS default endpoint
	// +kubebuilder:validation:Optional
	DefaultEndpoint *string `json:"defaultEndpoint,omitempty" tf:"default_endpoint,omitempty"`

	// AWS default endpoint CA (string)
	// AWS default endpoint CA
	// +kubebuilder:validation:Optional
	DefaultEndpointCASecretRef *v1.LocalSecretKeySelector `json:"defaultEndpointCaSecretRef,omitempty" tf:"-"`

	// AWS default folder (string)
	// AWS default folder
	// +kubebuilder:validation:Optional
	DefaultFolder *string `json:"defaultFolder,omitempty" tf:"default_folder,omitempty"`

	// AWS default region (string)
	// AWS default region
	// +kubebuilder:validation:Optional
	DefaultRegion *string `json:"defaultRegion,omitempty" tf:"default_region,omitempty"`

	// AWS default skip ssl verify. Default: false (bool)
	// AWS default skip ssl verify
	// +kubebuilder:validation:Optional
	DefaultSkipSSLVerify *bool `json:"defaultSkipSslVerify,omitempty" tf:"default_skip_ssl_verify,omitempty"`

	// AWS secret key (string)
	// AWS Secret Key
	// +kubebuilder:validation:Optional
	SecretKeySecretRef v1.LocalSecretKeySelector `json:"secretKeySecretRef" tf:"-"`
}

type VsphereCredentialConfigInitParameters struct {

	// OpenStack password (string)
	// vSphere password
	PasswordSecretRef v1.LocalSecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// vSphere username (string)
	// vSphere username
	Username *string `json:"username,omitempty" tf:"username,omitempty"`

	// vSphere IP/hostname for vCenter (string)
	// vSphere IP/hostname for vCenter
	Vcenter *string `json:"vcenter,omitempty" tf:"vcenter,omitempty"`

	// vSphere Port for vCenter. Default 443 (string)
	// vSphere Port for vCenter
	VcenterPort *string `json:"vcenterPort,omitempty" tf:"vcenter_port,omitempty"`
}

type VsphereCredentialConfigObservation struct {

	// vSphere username (string)
	// vSphere username
	Username *string `json:"username,omitempty" tf:"username,omitempty"`

	// vSphere IP/hostname for vCenter (string)
	// vSphere IP/hostname for vCenter
	Vcenter *string `json:"vcenter,omitempty" tf:"vcenter,omitempty"`

	// vSphere Port for vCenter. Default 443 (string)
	// vSphere Port for vCenter
	VcenterPort *string `json:"vcenterPort,omitempty" tf:"vcenter_port,omitempty"`
}

type VsphereCredentialConfigParameters struct {

	// OpenStack password (string)
	// vSphere password
	// +kubebuilder:validation:Optional
	PasswordSecretRef v1.LocalSecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// vSphere username (string)
	// vSphere username
	// +kubebuilder:validation:Optional
	Username *string `json:"username" tf:"username,omitempty"`

	// vSphere IP/hostname for vCenter (string)
	// vSphere IP/hostname for vCenter
	// +kubebuilder:validation:Optional
	Vcenter *string `json:"vcenter" tf:"vcenter,omitempty"`

	// vSphere Port for vCenter. Default 443 (string)
	// vSphere Port for vCenter
	// +kubebuilder:validation:Optional
	VcenterPort *string `json:"vcenterPort,omitempty" tf:"vcenter_port,omitempty"`
}

// CloudCredentialSpec defines the desired state of CloudCredential
type CloudCredentialSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            CloudCredentialParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CloudCredentialInitParameters `json:"initProvider,omitempty"`
}

// CloudCredentialStatus defines the observed state of CloudCredential.
type CloudCredentialStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CloudCredentialObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CloudCredential is the Schema for the CloudCredentials API. Provides a Rancher v2 Cloud Credential resource. This can be used to create Cloud Credential for Rancher v2.2.x and retrieve their information.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rancher2}
type CloudCredential struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   CloudCredentialSpec   `json:"spec"`
	Status CloudCredentialStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CloudCredentialList contains a list of CloudCredentials
type CloudCredentialList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CloudCredential `json:"items"`
}

// Repository type metadata.
var (
	CloudCredential_Kind             = "CloudCredential"
	CloudCredential_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CloudCredential_Kind}.String()
	CloudCredential_KindAPIVersion   = CloudCredential_Kind + "." + CRDGroupVersion.String()
	CloudCredential_GroupVersionKind = CRDGroupVersion.WithKind(CloudCredential_Kind)
)

func init() {
	SchemeBuilder.Register(&CloudCredential{}, &CloudCredentialList{})
}
