// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	"dario.cat/mergo"
	"github.com/pkg/errors"

	"github.com/crossplane/upjet/v2/pkg/resource"
	"github.com/crossplane/upjet/v2/pkg/resource/json"
)

// GetTerraformResourceType returns Terraform resource type for this CloudCredential
func (mg *CloudCredential) GetTerraformResourceType() string {
	return "rancher2_cloud_credential"
}

// GetConnectionDetailsMapping for this CloudCredential
func (tr *CloudCredential) GetConnectionDetailsMapping() map[string]string {
	return map[string]string{"amazonec2_credential_config[*].access_key": "amazonec2CredentialConfig[*].accessKeySecretRef", "amazonec2_credential_config[*].secret_key": "amazonec2CredentialConfig[*].secretKeySecretRef", "azure_credential_config[*].client_id": "azureCredentialConfig[*].clientIdSecretRef", "azure_credential_config[*].client_secret": "azureCredentialConfig[*].clientSecretSecretRef", "azure_credential_config[*].subscription_id": "azureCredentialConfig[*].subscriptionIdSecretRef", "digitalocean_credential_config[*].access_token": "digitaloceanCredentialConfig[*].accessTokenSecretRef", "google_credential_config[*].auth_encoded_json": "googleCredentialConfig[*].authEncodedJsonSecretRef", "harvester_credential_config[*].kubeconfig_content": "harvesterCredentialConfig[*].kubeconfigContentSecretRef", "linode_credential_config[*].token": "linodeCredentialConfig[*].tokenSecretRef", "openstack_credential_config[*].password": "openstackCredentialConfig[*].passwordSecretRef", "s3_credential_config[*].access_key": "s3CredentialConfig[*].accessKeySecretRef", "s3_credential_config[*].default_endpoint_ca": "s3CredentialConfig[*].defaultEndpointCaSecretRef", "s3_credential_config[*].secret_key": "s3CredentialConfig[*].secretKeySecretRef", "vsphere_credential_config[*].password": "vsphereCredentialConfig[*].passwordSecretRef"}
}

// GetObservation of this CloudCredential
func (tr *CloudCredential) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this CloudCredential
func (tr *CloudCredential) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this CloudCredential
func (tr *CloudCredential) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this CloudCredential
func (tr *CloudCredential) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this CloudCredential
func (tr *CloudCredential) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// GetInitParameters of this CloudCredential
func (tr *CloudCredential) GetInitParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.InitProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// GetInitParameters of this CloudCredential
func (tr *CloudCredential) GetMergedParameters(shouldMergeInitProvider bool) (map[string]any, error) {
	params, err := tr.GetParameters()
	if err != nil {
		return nil, errors.Wrapf(err, "cannot get parameters for resource \"%s/%s\"", tr.GetNamespace(), tr.GetName())
	}
	if !shouldMergeInitProvider {
		return params, nil
	}

	initParams, err := tr.GetInitParameters()
	if err != nil {
		return nil, errors.Wrapf(err, "cannot get init parameters for resource \"%s/%s\"", tr.GetNamespace(), tr.GetName())
	}

	// Note(lsviben): mergo.WithSliceDeepCopy is needed to merge the
	// slices from the initProvider to forProvider. As it also sets
	// overwrite to true, we need to set it back to false, we don't
	// want to overwrite the forProvider fields with the initProvider
	// fields.
	err = mergo.Merge(&params, initParams, mergo.WithSliceDeepCopy, func(c *mergo.Config) {
		c.Overwrite = false
	})
	if err != nil {
		return nil, errors.Wrapf(err, "cannot merge spec.initProvider and spec.forProvider parameters for resource \"%s/%s\"", tr.GetNamespace(), tr.GetName())
	}

	return params, nil
}

// LateInitialize this CloudCredential using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *CloudCredential) LateInitialize(attrs []byte) (bool, error) {
	params := &CloudCredentialParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *CloudCredential) GetTerraformSchemaVersion() int {
	return 0
}
