// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type GlobalRoleBindingInitParameters struct {

	// Annotations for global role binding (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The role id from create global role binding (string)
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/namespaced/rancher/v1alpha1.GlobalRole
	GlobalRoleID *string `json:"globalRoleId,omitempty" tf:"global_role_id,omitempty"`

	// Reference to a GlobalRole in rancher to populate globalRoleId.
	// +kubebuilder:validation:Optional
	GlobalRoleIDRef *v1.NamespacedReference `json:"globalRoleIdRef,omitempty" tf:"-"`

	// Selector for a GlobalRole in rancher to populate globalRoleId.
	// +kubebuilder:validation:Optional
	GlobalRoleIDSelector *v1.NamespacedSelector `json:"globalRoleIdSelector,omitempty" tf:"-"`

	// The group principal ID to assign global role binding (only works with external auth providers that support groups). Rancher v2.4.0 or higher is required (string)
	GroupPrincipalID *string `json:"groupPrincipalId,omitempty" tf:"group_principal_id,omitempty"`

	// Labels for global role binding (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the global role binding (string)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The user ID to assign global role binding (string)
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type GlobalRoleBindingObservation struct {

	// Annotations for global role binding (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The role id from create global role binding (string)
	GlobalRoleID *string `json:"globalRoleId,omitempty" tf:"global_role_id,omitempty"`

	// The group principal ID to assign global role binding (only works with external auth providers that support groups). Rancher v2.4.0 or higher is required (string)
	GroupPrincipalID *string `json:"groupPrincipalId,omitempty" tf:"group_principal_id,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels for global role binding (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the global role binding (string)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The user ID to assign global role binding (string)
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type GlobalRoleBindingParameters struct {

	// Annotations for global role binding (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The role id from create global role binding (string)
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/namespaced/rancher/v1alpha1.GlobalRole
	// +kubebuilder:validation:Optional
	GlobalRoleID *string `json:"globalRoleId,omitempty" tf:"global_role_id,omitempty"`

	// Reference to a GlobalRole in rancher to populate globalRoleId.
	// +kubebuilder:validation:Optional
	GlobalRoleIDRef *v1.NamespacedReference `json:"globalRoleIdRef,omitempty" tf:"-"`

	// Selector for a GlobalRole in rancher to populate globalRoleId.
	// +kubebuilder:validation:Optional
	GlobalRoleIDSelector *v1.NamespacedSelector `json:"globalRoleIdSelector,omitempty" tf:"-"`

	// The group principal ID to assign global role binding (only works with external auth providers that support groups). Rancher v2.4.0 or higher is required (string)
	// +kubebuilder:validation:Optional
	GroupPrincipalID *string `json:"groupPrincipalId,omitempty" tf:"group_principal_id,omitempty"`

	// Labels for global role binding (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the global role binding (string)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The user ID to assign global role binding (string)
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

// GlobalRoleBindingSpec defines the desired state of GlobalRoleBinding
type GlobalRoleBindingSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            GlobalRoleBindingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GlobalRoleBindingInitParameters `json:"initProvider,omitempty"`
}

// GlobalRoleBindingStatus defines the observed state of GlobalRoleBinding.
type GlobalRoleBindingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GlobalRoleBindingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GlobalRoleBinding is the Schema for the GlobalRoleBindings API. Provides a Rancher v2 Global Role Binding resource. This can be used to create Global Role Bindings for Rancher v2 environments and retrieve their information.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rancher2}
type GlobalRoleBinding struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GlobalRoleBindingSpec   `json:"spec"`
	Status            GlobalRoleBindingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GlobalRoleBindingList contains a list of GlobalRoleBindings
type GlobalRoleBindingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GlobalRoleBinding `json:"items"`
}

// Repository type metadata.
var (
	GlobalRoleBinding_Kind             = "GlobalRoleBinding"
	GlobalRoleBinding_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GlobalRoleBinding_Kind}.String()
	GlobalRoleBinding_KindAPIVersion   = GlobalRoleBinding_Kind + "." + CRDGroupVersion.String()
	GlobalRoleBinding_GroupVersionKind = CRDGroupVersion.WithKind(GlobalRoleBinding_Kind)
)

func init() {
	SchemeBuilder.Register(&GlobalRoleBinding{}, &GlobalRoleBindingList{})
}
