// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Bootstrap) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CloudCredential) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Cluster) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClusterDriver) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClusterRoleTemplateBinding) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClusterSync) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClusterV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CustomUserToken) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Feature) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GlobalRole) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GlobalRoleBinding) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MachineConfigV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NodeDriver) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NodePool) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RoleTemplate) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Setting) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Token) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *User) Hub() {}
