// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type NodePoolInitParameters struct {

	// Annotations for Node Pool object (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The RKE cluster id to use Node Pool (string)
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/namespaced/rancher/v1alpha1.ClusterV2
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// RKE control plane role for created nodes (bool)
	ControlPlane *bool `json:"controlPlane,omitempty" tf:"control_plane,omitempty"`

	// Delete not ready node after secs. For Rancher v2.3.3 and above. Default 0 (int)
	DeleteNotReadyAfterSecs *float64 `json:"deleteNotReadyAfterSecs,omitempty" tf:"delete_not_ready_after_secs,omitempty"`

	// Drain nodes before delete. Default: false (bool)
	DrainBeforeDelete *bool `json:"drainBeforeDelete,omitempty" tf:"drain_before_delete,omitempty"`

	// RKE etcd role for created nodes (bool)
	Etcd *bool `json:"etcd,omitempty" tf:"etcd,omitempty"`

	// The prefix for created nodes of the Node Pool (string)
	HostnamePrefix *string `json:"hostnamePrefix,omitempty" tf:"hostname_prefix,omitempty"`

	// Labels for Node Pool object (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the Node Pool (string)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Node taints. For Rancher v2.3.3 and above (List)
	NodeTaints []NodeTaintsInitParameters `json:"nodeTaints,omitempty" tf:"node_taints,omitempty"`

	// The Node Template ID to use for node creation (string)
	NodeTemplateID *string `json:"nodeTemplateId,omitempty" tf:"node_template_id,omitempty"`

	// The number of nodes to create on Node Pool. Default 1. Only values >= 1 allowed (int)
	Quantity *float64 `json:"quantity,omitempty" tf:"quantity,omitempty"`

	// RKE role role for created nodes (bool)
	Worker *bool `json:"worker,omitempty" tf:"worker,omitempty"`
}

type NodePoolObservation struct {

	// Annotations for Node Pool object (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The RKE cluster id to use Node Pool (string)
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// RKE control plane role for created nodes (bool)
	ControlPlane *bool `json:"controlPlane,omitempty" tf:"control_plane,omitempty"`

	// Delete not ready node after secs. For Rancher v2.3.3 and above. Default 0 (int)
	DeleteNotReadyAfterSecs *float64 `json:"deleteNotReadyAfterSecs,omitempty" tf:"delete_not_ready_after_secs,omitempty"`

	// Drain nodes before delete. Default: false (bool)
	DrainBeforeDelete *bool `json:"drainBeforeDelete,omitempty" tf:"drain_before_delete,omitempty"`

	// RKE etcd role for created nodes (bool)
	Etcd *bool `json:"etcd,omitempty" tf:"etcd,omitempty"`

	// The prefix for created nodes of the Node Pool (string)
	HostnamePrefix *string `json:"hostnamePrefix,omitempty" tf:"hostname_prefix,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels for Node Pool object (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the Node Pool (string)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Node taints. For Rancher v2.3.3 and above (List)
	NodeTaints []NodeTaintsObservation `json:"nodeTaints,omitempty" tf:"node_taints,omitempty"`

	// The Node Template ID to use for node creation (string)
	NodeTemplateID *string `json:"nodeTemplateId,omitempty" tf:"node_template_id,omitempty"`

	// The number of nodes to create on Node Pool. Default 1. Only values >= 1 allowed (int)
	Quantity *float64 `json:"quantity,omitempty" tf:"quantity,omitempty"`

	// RKE role role for created nodes (bool)
	Worker *bool `json:"worker,omitempty" tf:"worker,omitempty"`
}

type NodePoolParameters struct {

	// Annotations for Node Pool object (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The RKE cluster id to use Node Pool (string)
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/namespaced/rancher/v1alpha1.ClusterV2
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// RKE control plane role for created nodes (bool)
	// +kubebuilder:validation:Optional
	ControlPlane *bool `json:"controlPlane,omitempty" tf:"control_plane,omitempty"`

	// Delete not ready node after secs. For Rancher v2.3.3 and above. Default 0 (int)
	// +kubebuilder:validation:Optional
	DeleteNotReadyAfterSecs *float64 `json:"deleteNotReadyAfterSecs,omitempty" tf:"delete_not_ready_after_secs,omitempty"`

	// Drain nodes before delete. Default: false (bool)
	// +kubebuilder:validation:Optional
	DrainBeforeDelete *bool `json:"drainBeforeDelete,omitempty" tf:"drain_before_delete,omitempty"`

	// RKE etcd role for created nodes (bool)
	// +kubebuilder:validation:Optional
	Etcd *bool `json:"etcd,omitempty" tf:"etcd,omitempty"`

	// The prefix for created nodes of the Node Pool (string)
	// +kubebuilder:validation:Optional
	HostnamePrefix *string `json:"hostnamePrefix,omitempty" tf:"hostname_prefix,omitempty"`

	// Labels for Node Pool object (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the Node Pool (string)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Node taints. For Rancher v2.3.3 and above (List)
	// +kubebuilder:validation:Optional
	NodeTaints []NodeTaintsParameters `json:"nodeTaints,omitempty" tf:"node_taints,omitempty"`

	// The Node Template ID to use for node creation (string)
	// +kubebuilder:validation:Optional
	NodeTemplateID *string `json:"nodeTemplateId,omitempty" tf:"node_template_id,omitempty"`

	// The number of nodes to create on Node Pool. Default 1. Only values >= 1 allowed (int)
	// +kubebuilder:validation:Optional
	Quantity *float64 `json:"quantity,omitempty" tf:"quantity,omitempty"`

	// RKE role role for created nodes (bool)
	// +kubebuilder:validation:Optional
	Worker *bool `json:"worker,omitempty" tf:"worker,omitempty"`
}

type NodeTaintsInitParameters struct {

	// Taint effect. Supported values : "NoExecute" | "NoSchedule" | "PreferNoSchedule" (string)
	Effect *string `json:"effect,omitempty" tf:"effect,omitempty"`

	// Taint key (string)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// Taint time added (string)
	TimeAdded *string `json:"timeAdded,omitempty" tf:"time_added,omitempty"`

	// Taint value (string)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type NodeTaintsObservation struct {

	// Taint effect. Supported values : "NoExecute" | "NoSchedule" | "PreferNoSchedule" (string)
	Effect *string `json:"effect,omitempty" tf:"effect,omitempty"`

	// Taint key (string)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// Taint time added (string)
	TimeAdded *string `json:"timeAdded,omitempty" tf:"time_added,omitempty"`

	// Taint value (string)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type NodeTaintsParameters struct {

	// Taint effect. Supported values : "NoExecute" | "NoSchedule" | "PreferNoSchedule" (string)
	// +kubebuilder:validation:Optional
	Effect *string `json:"effect,omitempty" tf:"effect,omitempty"`

	// Taint key (string)
	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// Taint time added (string)
	// +kubebuilder:validation:Optional
	TimeAdded *string `json:"timeAdded,omitempty" tf:"time_added,omitempty"`

	// Taint value (string)
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

// NodePoolSpec defines the desired state of NodePool
type NodePoolSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            NodePoolParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NodePoolInitParameters `json:"initProvider,omitempty"`
}

// NodePoolStatus defines the observed state of NodePool.
type NodePoolStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NodePoolObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NodePool is the Schema for the NodePools API. Provides a Rancher v2 Node Pool resource. This can be used to create Node Pool, using Node template for Rancher v2 RKE clusters and retrieve their information.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rancher2}
type NodePool struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.hostnamePrefix) || (has(self.initProvider) && has(self.initProvider.hostnamePrefix))",message="spec.forProvider.hostnamePrefix is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.nodeTemplateId) || (has(self.initProvider) && has(self.initProvider.nodeTemplateId))",message="spec.forProvider.nodeTemplateId is a required parameter"
	Spec   NodePoolSpec   `json:"spec"`
	Status NodePoolStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NodePoolList contains a list of NodePools
type NodePoolList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NodePool `json:"items"`
}

// Repository type metadata.
var (
	NodePool_Kind             = "NodePool"
	NodePool_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NodePool_Kind}.String()
	NodePool_KindAPIVersion   = NodePool_Kind + "." + CRDGroupVersion.String()
	NodePool_GroupVersionKind = CRDGroupVersion.WithKind(NodePool_Kind)
)

func init() {
	SchemeBuilder.Register(&NodePool{}, &NodePoolList{})
}
