apiVersion: rancher.rancher2.contrib.crossplane.io/v1alpha1
kind: CloudCredential
metadata:
  annotations:
    meta.upbound.io/example-id: rancher/v1alpha1/cloudcredential
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    amazonec2CredentialConfig:
    - accessKeySecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
      secretKeySecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
    description: foo test
    name: foo
