apiVersion: rancher.rancher2.contrib.crossplane.io/v1alpha1
kind: Feature
metadata:
  annotations:
    meta.upbound.io/example-id: rancher/v1alpha1/feature
  labels:
    testing.upbound.io/example-name: fleet
  name: fleet
spec:
  forProvider:
    name: fleet
    value: <VALUE>
