// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ConfigMapV2InitParameters struct {

	// Annotations for the configMap v2 (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The cluster id of the configMap V2 (string)
	// K8s cluster ID
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/namespaced/rancher/v1alpha1.ClusterV2
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// The data of the configMap v2 (map)
	// ConfigMap V2 data map
	// +mapType=granular
	Data map[string]*string `json:"data,omitempty" tf:"data,omitempty"`

	// If set to true, any configMap update will remove and recreate the configMap. This is a beta field enabled by k8s ImmutableEphemeralVolumes feature gate. Default: false (bool)
	// If set to true, ensures that data stored in the ConfigMap cannot be updated
	Immutable *bool `json:"immutable,omitempty" tf:"immutable,omitempty"`

	// Labels for the configMap v2 (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the configMap v2 (string)
	// ConfigMap V2 name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The namespaces of the configMap v2. Default: default (string)
	// ConfigMap V2 namespace
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/namespaced/k8s/v1alpha1.Namespace
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Reference to a Namespace in k8s to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceRef *v1.NamespacedReference `json:"namespaceRef,omitempty" tf:"-"`

	// Selector for a Namespace in k8s to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceSelector *v1.NamespacedSelector `json:"namespaceSelector,omitempty" tf:"-"`
}

type ConfigMapV2Observation struct {

	// Annotations for the configMap v2 (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The cluster id of the configMap V2 (string)
	// K8s cluster ID
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// The data of the configMap v2 (map)
	// ConfigMap V2 data map
	// +mapType=granular
	Data map[string]*string `json:"data,omitempty" tf:"data,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// If set to true, any configMap update will remove and recreate the configMap. This is a beta field enabled by k8s ImmutableEphemeralVolumes feature gate. Default: false (bool)
	// If set to true, ensures that data stored in the ConfigMap cannot be updated
	Immutable *bool `json:"immutable,omitempty" tf:"immutable,omitempty"`

	// Labels for the configMap v2 (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the configMap v2 (string)
	// ConfigMap V2 name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The namespaces of the configMap v2. Default: default (string)
	// ConfigMap V2 namespace
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (Computed) The k8s resource version (string)
	ResourceVersion *string `json:"resourceVersion,omitempty" tf:"resource_version,omitempty"`
}

type ConfigMapV2Parameters struct {

	// Annotations for the configMap v2 (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The cluster id of the configMap V2 (string)
	// K8s cluster ID
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/namespaced/rancher/v1alpha1.ClusterV2
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// The data of the configMap v2 (map)
	// ConfigMap V2 data map
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Data map[string]*string `json:"data,omitempty" tf:"data,omitempty"`

	// If set to true, any configMap update will remove and recreate the configMap. This is a beta field enabled by k8s ImmutableEphemeralVolumes feature gate. Default: false (bool)
	// If set to true, ensures that data stored in the ConfigMap cannot be updated
	// +kubebuilder:validation:Optional
	Immutable *bool `json:"immutable,omitempty" tf:"immutable,omitempty"`

	// Labels for the configMap v2 (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the configMap v2 (string)
	// ConfigMap V2 name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The namespaces of the configMap v2. Default: default (string)
	// ConfigMap V2 namespace
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/namespaced/k8s/v1alpha1.Namespace
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Reference to a Namespace in k8s to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceRef *v1.NamespacedReference `json:"namespaceRef,omitempty" tf:"-"`

	// Selector for a Namespace in k8s to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceSelector *v1.NamespacedSelector `json:"namespaceSelector,omitempty" tf:"-"`
}

// ConfigMapV2Spec defines the desired state of ConfigMapV2
type ConfigMapV2Spec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ConfigMapV2Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ConfigMapV2InitParameters `json:"initProvider,omitempty"`
}

// ConfigMapV2Status defines the observed state of ConfigMapV2.
type ConfigMapV2Status struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ConfigMapV2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ConfigMapV2 is the Schema for the ConfigMapV2s API. Provides a Rancher ConfigMap v2 resource. This can be used to create k8s configMaps for Rancher v2 environments and retrieve their information. ConfigMap v2 resource is available at Rancher v2.5.x and above.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rancher2}
type ConfigMapV2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.data) || (has(self.initProvider) && has(self.initProvider.data))",message="spec.forProvider.data is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ConfigMapV2Spec   `json:"spec"`
	Status ConfigMapV2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ConfigMapV2List contains a list of ConfigMapV2s
type ConfigMapV2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ConfigMapV2 `json:"items"`
}

// Repository type metadata.
var (
	ConfigMapV2_Kind             = "ConfigMapV2"
	ConfigMapV2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ConfigMapV2_Kind}.String()
	ConfigMapV2_KindAPIVersion   = ConfigMapV2_Kind + "." + CRDGroupVersion.String()
	ConfigMapV2_GroupVersionKind = CRDGroupVersion.WithKind(ConfigMapV2_Kind)
)

func init() {
	SchemeBuilder.Register(&ConfigMapV2{}, &ConfigMapV2List{})
}
