// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type RegistriesInitParameters struct {

	// Address for registry.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// Password for the registry (string)
	PasswordSecretRef *v1.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// Username for the registry (string)
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type RegistriesObservation struct {

	// Address for registry.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// Username for the registry (string)
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type RegistriesParameters struct {

	// Address for registry.
	// +kubebuilder:validation:Optional
	Address *string `json:"address" tf:"address,omitempty"`

	// Password for the registry (string)
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v1.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// Username for the registry (string)
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type RegistryInitParameters struct {

	// Annotations for Registry object (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// A registry description (string)
	// Description of the docker registry
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Labels for Registry object (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the registry (string)
	// Name of the docker registry
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// in the project_id.
	// Namespace ID to add docker registry
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/namespaced/k8s/v1alpha1.Namespace
	NamespaceID *string `json:"namespaceId,omitempty" tf:"namespace_id,omitempty"`

	// Reference to a Namespace in k8s to populate namespaceId.
	// +kubebuilder:validation:Optional
	NamespaceIDRef *v1.NamespacedReference `json:"namespaceIdRef,omitempty" tf:"-"`

	// Selector for a Namespace in k8s to populate namespaceId.
	// +kubebuilder:validation:Optional
	NamespaceIDSelector *v1.NamespacedSelector `json:"namespaceIdSelector,omitempty" tf:"-"`

	// .
	// Project ID to add docker registry
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/namespaced/k8s/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in k8s to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in k8s to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// Registries data for registry (list)
	Registries []RegistriesInitParameters `json:"registries,omitempty" tf:"registries,omitempty"`
}

type RegistryObservation struct {

	// Annotations for Registry object (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// A registry description (string)
	// Description of the docker registry
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels for Registry object (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the registry (string)
	// Name of the docker registry
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// in the project_id.
	// Namespace ID to add docker registry
	NamespaceID *string `json:"namespaceId,omitempty" tf:"namespace_id,omitempty"`

	// .
	// Project ID to add docker registry
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Registries data for registry (list)
	Registries []RegistriesObservation `json:"registries,omitempty" tf:"registries,omitempty"`
}

type RegistryParameters struct {

	// Annotations for Registry object (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// A registry description (string)
	// Description of the docker registry
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Labels for Registry object (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the registry (string)
	// Name of the docker registry
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// in the project_id.
	// Namespace ID to add docker registry
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/namespaced/k8s/v1alpha1.Namespace
	// +kubebuilder:validation:Optional
	NamespaceID *string `json:"namespaceId,omitempty" tf:"namespace_id,omitempty"`

	// Reference to a Namespace in k8s to populate namespaceId.
	// +kubebuilder:validation:Optional
	NamespaceIDRef *v1.NamespacedReference `json:"namespaceIdRef,omitempty" tf:"-"`

	// Selector for a Namespace in k8s to populate namespaceId.
	// +kubebuilder:validation:Optional
	NamespaceIDSelector *v1.NamespacedSelector `json:"namespaceIdSelector,omitempty" tf:"-"`

	// .
	// Project ID to add docker registry
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/namespaced/k8s/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in k8s to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in k8s to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// Registries data for registry (list)
	// +kubebuilder:validation:Optional
	Registries []RegistriesParameters `json:"registries,omitempty" tf:"registries,omitempty"`
}

// RegistrySpec defines the desired state of Registry
type RegistrySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RegistryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RegistryInitParameters `json:"initProvider,omitempty"`
}

// RegistryStatus defines the observed state of Registry.
type RegistryStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RegistryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Registry is the Schema for the Registrys API. Provides a Rancher v2 Registry resource. This resource creates Kubernetes secrets with the type
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rancher2}
type Registry struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.registries) || (has(self.initProvider) && has(self.initProvider.registries))",message="spec.forProvider.registries is a required parameter"
	Spec   RegistrySpec   `json:"spec"`
	Status RegistryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RegistryList contains a list of Registrys
type RegistryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Registry `json:"items"`
}

// Repository type metadata.
var (
	Registry_Kind             = "Registry"
	Registry_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Registry_Kind}.String()
	Registry_KindAPIVersion   = Registry_Kind + "." + CRDGroupVersion.String()
	Registry_GroupVersionKind = CRDGroupVersion.WithKind(Registry_Kind)
)

func init() {
	SchemeBuilder.Register(&Registry{}, &RegistryList{})
}
