// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type SecretV2InitParameters struct {

	// Annotations for the secret v2 (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The cluster id of the secret V2 (string)
	// K8s cluster ID
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/namespaced/rancher/v1alpha1.ClusterV2
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	Data map[string]*string `json:"dataSecretRef" tf:"-"`

	// If set to true, any secret update will remove and recreate the secret. This is a beta field enabled by k8s ImmutableEphemeralVolumes feature gate. Default: false (bool)
	// If set to true, ensures that data stored in the Secret cannot be updated
	Immutable *bool `json:"immutable,omitempty" tf:"immutable,omitempty"`

	// Labels for the secret v2 (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the secret v2 (string)
	// K8s Secret name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The namespaces of the secret v2. Default: default (string)
	// K8s Secret namespace
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/namespaced/k8s/v1alpha1.Namespace
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Reference to a Namespace in k8s to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceRef *v1.NamespacedReference `json:"namespaceRef,omitempty" tf:"-"`

	// Selector for a Namespace in k8s to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceSelector *v1.NamespacedSelector `json:"namespaceSelector,omitempty" tf:"-"`

	// The type of the k8s secret, used to facilitate programmatic handling of secret data, More info about k8s secret types and expected format.  Default: Opaque (string)
	// Used to facilitate programmatic handling of Secret data
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type SecretV2Observation struct {

	// Annotations for the secret v2 (map)
	// Annotations of the resource
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The cluster id of the secret V2 (string)
	// K8s cluster ID
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (Computed) The ID of the resource (string)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// If set to true, any secret update will remove and recreate the secret. This is a beta field enabled by k8s ImmutableEphemeralVolumes feature gate. Default: false (bool)
	// If set to true, ensures that data stored in the Secret cannot be updated
	Immutable *bool `json:"immutable,omitempty" tf:"immutable,omitempty"`

	// Labels for the secret v2 (map)
	// Labels of the resource
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the secret v2 (string)
	// K8s Secret name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The namespaces of the secret v2. Default: default (string)
	// K8s Secret namespace
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (Computed) The k8s resource version (string)
	ResourceVersion *string `json:"resourceVersion,omitempty" tf:"resource_version,omitempty"`

	// The type of the k8s secret, used to facilitate programmatic handling of secret data, More info about k8s secret types and expected format.  Default: Opaque (string)
	// Used to facilitate programmatic handling of Secret data
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type SecretV2Parameters struct {

	// Annotations for the secret v2 (map)
	// Annotations of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// The cluster id of the secret V2 (string)
	// K8s cluster ID
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/namespaced/rancher/v1alpha1.ClusterV2
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a ClusterV2 in rancher to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// The data of the secret v2 (map)
	// Secret data map
	// +kubebuilder:validation:Optional
	DataSecretRef v1.LocalSecretReference `json:"dataSecretRef" tf:"-"`

	// If set to true, any secret update will remove and recreate the secret. This is a beta field enabled by k8s ImmutableEphemeralVolumes feature gate. Default: false (bool)
	// If set to true, ensures that data stored in the Secret cannot be updated
	// +kubebuilder:validation:Optional
	Immutable *bool `json:"immutable,omitempty" tf:"immutable,omitempty"`

	// Labels for the secret v2 (map)
	// Labels of the resource
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the secret v2 (string)
	// K8s Secret name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The namespaces of the secret v2. Default: default (string)
	// K8s Secret namespace
	// +crossplane:generate:reference:type=github.com/disaster37/provider-rancher2/apis/namespaced/k8s/v1alpha1.Namespace
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Reference to a Namespace in k8s to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceRef *v1.NamespacedReference `json:"namespaceRef,omitempty" tf:"-"`

	// Selector for a Namespace in k8s to populate namespace.
	// +kubebuilder:validation:Optional
	NamespaceSelector *v1.NamespacedSelector `json:"namespaceSelector,omitempty" tf:"-"`

	// The type of the k8s secret, used to facilitate programmatic handling of secret data, More info about k8s secret types and expected format.  Default: Opaque (string)
	// Used to facilitate programmatic handling of Secret data
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// SecretV2Spec defines the desired state of SecretV2
type SecretV2Spec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SecretV2Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SecretV2InitParameters `json:"initProvider,omitempty"`
}

// SecretV2Status defines the observed state of SecretV2.
type SecretV2Status struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SecretV2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SecretV2 is the Schema for the SecretV2s API. Provides a Rancher Secret v2 resource. This can be used to create k8s secrets for Rancher v2 environments and retrieve their information. Secret v2 resource is available at Rancher v2.5.x and above.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rancher2}
type SecretV2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.dataSecretRef)",message="spec.forProvider.dataSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   SecretV2Spec   `json:"spec"`
	Status SecretV2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SecretV2List contains a list of SecretV2s
type SecretV2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SecretV2 `json:"items"`
}

// Repository type metadata.
var (
	SecretV2_Kind             = "SecretV2"
	SecretV2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SecretV2_Kind}.String()
	SecretV2_KindAPIVersion   = SecretV2_Kind + "." + CRDGroupVersion.String()
	SecretV2_GroupVersionKind = CRDGroupVersion.WithKind(SecretV2_Kind)
)

func init() {
	SchemeBuilder.Register(&SecretV2{}, &SecretV2List{})
}
